/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface NSIndexPath (SBIconIndex)
+ (id)indexPathWithIconIndex:(NSUInteger)arg1 listIndex:(NSUInteger)arg2;
+ (id)emptyPath;
- (BOOL)isPrefixedByPath:(id)arg1;
- (id)indexPathWithPrefixPath:(id)arg1;
- (id)subpathFromPosition:(NSUInteger)arg1;
- (id)_subpathWithRange:(NSRange)arg1;
@end

