/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBToAppWorkspaceTransaction.h"

@class SBAwayController;

__attribute__((visibility("hidden")))
@interface SBActivateAppUnderLockScreenWorkspaceTransaction : SBToAppWorkspaceTransaction {
	SBAwayController* _awayController;
}
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(BOOL)selfWorkspaceDidResume;
-(BOOL)selfApplicationDidBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfAlertDidActivate:(id)selfAlert overAlerts:(id)alerts;
-(void)_handleAppActivationFailure;
-(void)_commit;
-(BOOL)shouldPerformToAppStateCleanupOnCompletion;
-(BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace alertManager:(id)manager application:(id)application awayController:(id)controller;
@end

