/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, SBAppSwitcherVolumeSlider, UIView;

__attribute__((visibility("hidden")))
@interface SBAirPlayBarView : XXUnknownSuperclass {
	UIView* _speakerIcon;
	UIButton* _airPlayButton;
	SBAppSwitcherVolumeSlider* _volumeSlider;
	BOOL _airPlayEnabled;
}
@property(assign, nonatomic, getter=isAirPlayEnabled) BOOL airPlayEnabled;
@property(readonly, assign, nonatomic) UIButton* airPlayButton;
@property(readonly, assign, nonatomic) SBAppSwitcherVolumeSlider* volumeSlider;
-(void)setAirPlayEnabled:(BOOL)enabled animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

