/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAlertManagerDelegate <NSObject>
-(void)alertManager:(id)manager didDeactivateAlert:(id)alert overAlerts:(id)alerts;
-(void)alertManager:(id)manager willDeactivateAlert:(id)alert overAlerts:(id)alerts;
-(void)alertManager:(id)manager didActivateAlert:(id)alert overAlerts:(id)alerts;
-(void)alertManager:(id)manager willActivateAlert:(id)alert overAlerts:(id)alerts;
@end

