/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDisplayProtocol.h"

@class SBActivationContext, NSMapTable, NSHashTable, SBAlertView, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBAlert : XXUnknownSuperclass <SBDisplayProtocol> {
	SBAlertView* _display;
	NSMutableDictionary* _dictionary;
	BOOL _SEO;
	SBActivationContext* _activationContext;
	NSMapTable* _displayValues;
	NSHashTable* _displayFlags;
	BOOL _orientationChangedEventsEnabled;
	float _accelerometerSampleInterval;
	BOOL _expectsFaceContact;
	BOOL _expectsFaceContactInLandscape;
}
@property(assign, nonatomic) BOOL SEO;
@property(copy, nonatomic) SBActivationContext* activationContext;
+(id)_adapterForController:(id)controller;
+(void)alertAdapterDisplayDidDisappear:(id)alertAdapterDisplay;
+(void)deactivateAlertForController:(id)controller animated:(BOOL)animated animateOldDisplayInWithStyle:(int)style isSlidingDisplay:(BOOL)display;
+(void)activateAlertForController:(id)controller animated:(BOOL)animated animateCurrentDisplayOut:(BOOL)anOut withDelay:(BOOL)delay isSlidingDisplay:(BOOL)display;
+(void)test;
+(id)alertWindow;
+(void)registerForAlerts;
-(BOOL)suppressesNotifications;
-(void)handleAutoLock;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(BOOL)handleVolumeDownButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleLockButtonPressed;
-(BOOL)hasTranslucentBackground;
-(BOOL)shouldPendAlertItemsWhileActive;
-(BOOL)shouldDeactivateAlertItemsOnActivation;
-(BOOL)handleMenuButtonTap;
-(void)animateDeactivation;
-(BOOL)currentlyAnimatingDeactivation;
-(void)didFinishAnimatingOut;
-(void)didFinishAnimatingIn;
-(void)didAnimateLockKeypadOut;
-(void)didAnimateLockKeypadIn;
-(int)statusBarStyle;
-(double)autoLockTime;
-(double)autoDimTime;
-(BOOL)allowsEventOnlySuspension;
-(BOOL)expectsFaceContactInLandscape;
-(BOOL)expectsFaceContact;
-(void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
-(void)setExpectsFaceContact:(BOOL)contact;
-(int)effectiveStatusBarStyle;
-(double)accelerometerSampleInterval;
-(void)setAccelerometerSampleInterval:(double)interval;
-(BOOL)orientationChangedEventsEnabled;
-(void)setOrientationChangedEventsEnabled:(BOOL)enabled;
-(id)description;
-(void)deactivate;
-(void)removeFromView;
-(int)interfaceOrientationForActivation;
-(void)activate;
-(int)statusBarStyleOverridesToCancel;
-(Class)alertWindowClass;
-(CGRect)alertWindowRect;
-(float)finalAlpha;
-(BOOL)showsSpringBoardStatusBar;
-(BOOL)undimsDisplay;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(void)removeObjectForKey:(id)key;
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(id)deactivationValue:(unsigned)value;
-(BOOL)deactivationFlag:(unsigned)flag;
-(void)setDeactivationSetting:(unsigned)setting value:(id)value;
-(void)setDeactivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDeactivationSettings;
-(id)activationValue:(unsigned)value;
-(BOOL)activationFlag:(unsigned)flag;
-(void)setActivationSetting:(unsigned)setting value:(id)value;
-(void)setActivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearActivationSettings;
-(BOOL)displayFlag:(unsigned)flag;
-(id)displayValue:(unsigned)value;
-(void)setDisplaySetting:(unsigned)setting value:(id)value;
-(void)setDisplaySetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDisplaySettings;
-(void)clearDisplay;
-(void)setDisplay:(id)display;
-(id)display;
-(void)dealloc;
-(id)init;
@end

