/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBAlertImageView : XXUnknownSuperclass {
	UIImageView* _imageView;
	UILabel* _labelView;
}
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame errorString:(id)string;
@end

