/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransaction.h"

@class SBAlert;

__attribute__((visibility("hidden")))
@interface SBAlertToAlertWorkspaceTransaction : SBWorkspaceTransaction {
	SBAlert* _activatingAlert;
	SBAlert* _deactivatingAlert;
	BOOL _activation;
}
-(BOOL)alertDidDeactivate:(id)alert overAlerts:(id)alerts;
-(BOOL)selfAlertWillDeactivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertDidActivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertWillActivate:(id)selfAlert overAlerts:(id)alerts;
-(void)_commit;
-(id)debugDescription;
-(void)dealloc;
-(id)_initWithWorkspace:(id)workspace alertManager:(id)manager activatingAlert:(id)alert deactivatingAlert:(id)alert4 activation:(BOOL)activation;
-(id)initDeactivationWithWorkspace:(id)workspace alertManager:(id)manager from:(id)from to:(id)to;
-(id)initActivationWithWorkspace:(id)workspace alertManager:(id)manager from:(id)from to:(id)to;
@end

