/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBToAppWorkspaceTransaction.h"
#import "SBUIAnimationControllerDelegate.h"

@class SBUIAnimationController, SBAlert;

__attribute__((visibility("hidden")))
@interface SBAlertToAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerDelegate> {
	SBAlert* _alert;
	SBUIAnimationController* _animation;
	BOOL _animatedAppActivation;
	BOOL _animatingAlertSuspension;
	BOOL _deactivateAfterNextLaunch;
	BOOL _activatingFromAssistant;
	BOOL _fadeAssistant;
}
@property(readonly, assign, nonatomic) SBAlert* alert;
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller didCommitAnimation:(BOOL)animation withDuration:(double)duration afterDelay:(double)delay;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(void)_handleFailure;
-(void)_deactivateAlertIfNecessary;
-(void)_alertAnimationComplete:(id)complete;
-(void)_transactionComplete;
-(void)_endAnimation;
-(BOOL)shouldPerformToAppStateCleanupOnCompletion;
-(BOOL)selfAlertDidDeactivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertWillDeactivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(BOOL)selfApplicationDidFinishLaunching:(id)selfApplication withInfo:(id)info;
-(BOOL)selfApplicationDidBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationWillBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationActivated:(id)activated;
-(void)_commit;
-(id)debugDescription;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace alertManager:(id)manager alert:(id)alert toApplication:(id)application;
@end

