/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "BBObserverDelegate.h"

@class NSMutableSet, CPDistributedNotificationCenter, BBObserver, NSMutableArray, NSTimer, NSArray;

__attribute__((visibility("hidden")))
@interface SBAlertItemsController : XXUnknownSuperclass <BBObserverDelegate> {
	NSMutableArray* _lockedAlertItems;
	NSMutableArray* _unlockedAlertItems;
	NSMutableArray* _pendingAlertItems;
	NSMutableArray* _superModalAlertItems;
	NSTimer* _autoDismissTimer;
	CPDistributedNotificationCenter* _notificationCenter;
	unsigned _notificationClientCount;
	BOOL _systemShuttingDown;
	NSMutableSet* _forceAlertsToPendReasons;
	BBObserver* _bbObserver;
}
@property(readonly, assign, nonatomic) NSArray* lockedAlertItems;
+(id)sharedInstance;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)_buddyDidExit;
-(void)_notificationClientEnded:(id)ended;
-(void)_notificationClientStarted:(id)started;
-(void)moveActiveAlertsToPendingWithAnimation:(BOOL)animation;
-(void)setForceAlertsToPend:(BOOL)pend forReason:(id)reason;
-(void)noteSystemShuttingDown;
-(void)notifySystemOfAlertItemActivation:(id)alertItemActivation;
-(void)_postAlertPresentedNotificationForType:(int)type sender:(id)sender date:(id)date;
-(void)noteVolumeOrLockPressedOverLockedAlerts;
-(void)deactivateAlertItemsForAlertActivationAndPendMiniAlerts:(BOOL)alertActivationAndPendMiniAlerts;
-(BOOL)dontLockOverAlertItems;
-(BOOL)deactivateAlertForMenuClickOrSystemGestureWithAnimation:(BOOL)animation;
-(BOOL)canDeactivateAlertForMenuClickOrSystemGesture;
-(id)visibleAlertItem;
-(BOOL)hasVisibleAlert;
-(BOOL)hasAlerts;
-(BOOL)hasAlertOfClass:(Class)aClass;
-(id)alertItemsOfClass:(Class)aClass;
-(id)alertItemOfClass:(Class)aClass;
-(void)autoDismissAlertItem:(id)item;
-(void)deactivateVisibleAlertItemOfClass:(Class)aClass reason:(int)reason;
-(void)deactivateAlertItemsOfClass:(Class)aClass reason:(int)reason animated:(BOOL)animated;
-(void)deactivateAlertItemsOfClass:(Class)aClass reason:(int)reason;
-(void)deactivateAlertItemsOfClass:(Class)aClass;
-(void)deactivateAlertItem:(id)item;
-(void)deactivateAlertItem:(id)item reason:(int)reason animated:(BOOL)animated;
-(void)activatePendedAlertsIfNecessary;
-(void)_activateSuperModalAlertsIfNecessary;
-(void)deactivateAlertItem:(id)item reason:(int)reason;
-(void)activateAlertItem:(id)item;
-(void)resetAutoDismissTimer;
-(void)convertUnlockedAlertsToLockedAlerts;
-(id)description;
-(BOOL)hasVisibleSuperModalAlert;
-(void)dealloc;
-(id)init;
@end

