/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSTimer;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherModel : XXUnknownSuperclass {
	NSMutableArray* _recentDisplayIdentifiers;
	NSTimer* _saveTimer;
}
+(id)sharedInstance;
-(id)snapshot;
-(void)appsRemoved:(id)removed added:(id)added;
-(id)identifiers;
-(unsigned)count;
-(id)identifierAtIndex:(unsigned)index;
-(id)appAtIndex:(unsigned)index;
-(void)remove:(id)remove;
-(void)addToFront:(id)front;
-(id)_recentsFromPrefs;
-(void)_saveRecents;
-(void)_saveRecentsDelayed;
-(void)_invalidateSaveTimer;
-(void)dealloc;
-(id)init;
@end

