/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconViewDelegate.h"
#import "SBIconViewMapDelegate.h"
#import "SBAppSwitcherBarViewDelegate.h"
#import "SBShowcaseViewController.h"

@class SBNowPlayingBar, NSString, SBPrintStatusController, SBAppSwitcherModel, SBAppSwitcherBarView;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherController : SBShowcaseViewController <SBIconViewDelegate, SBAppSwitcherBarViewDelegate, SBIconViewMapDelegate> {
	SBAppSwitcherModel* _model;
	SBNowPlayingBar* _nowPlayingBar;
	SBAppSwitcherBarView* _bottomBar;
	BOOL _editing;
	int _orientation;
	NSString* _topAppDisplayID;
	SBPrintStatusController* _printStatusController;
}
@property(retain) NSString* topAppDisplayID;
@property(readonly, assign, nonatomic) SBAppSwitcherModel* model;
+(id)sharedInstanceIfAvailable;
+(id)sharedInstance;
-(void)restoreScrollPositionAfterSuspendGesture;
-(void)saveScrollPositionBeforeSuspendGesture;
-(void)appSwitcherBar:(id)bar pageAtIndexDidDisappear:(int)pageAtIndex;
-(void)appSwitcherBar:(id)bar pageAtIndexDidAppear:(int)pageAtIndex;
-(BOOL)appSwitcherBar:(id)bar scrollShouldCancelInContentForView:(id)scroll;
-(void)appSwitcherBarRemovedFromSuperview:(id)superview;
-(BOOL)iconViewDisplaysBadges:(id)badges;
-(void)iconCloseBoxTapped:(id)tapped;
-(int)closeBoxTypeForIcon:(id)icon;
-(void)iconTouchBegan:(id)began;
-(void)iconHandleLongPress:(id)press;
-(BOOL)iconShouldAllowTap:(id)icon;
-(void)iconTapped:(id)tapped;
-(Class)viewMap:(id)map iconViewClassForIcon:(id)icon;
-(int)viewMap:(id)map locationForIcon:(id)icon;
-(unsigned)viewMap:(id)map maxRecycledIconViewsOfClass:(Class)aClass;
-(BOOL)printViewIsShowing;
-(id)printIconView;
-(void)dismissPrintView;
-(void)removePrintStatusIconBadge;
-(void)setNeedsPrintStatusIcon:(BOOL)icon;
-(void)_appActivationStateDidChange:(id)_appActivationState;
-(id)_currentDownloads;
-(void)_removeApplicationFromRecents:(id)recents;
-(void)_stopEditing;
-(void)_beginEditing;
-(BOOL)_inEditMode;
-(id)_bundleIdentifiersForViewDisplay;
-(BOOL)airPlayControlsVisible;
-(BOOL)nowPlayingControlsVisible;
-(BOOL)isScrolling;
-(BOOL)handleMenuButtonTap;
-(void)_iconModelVisibilityChanged:(id)changed;
-(void)_iconModelChangedSignificantly;
-(void)setupForApp:(id)app orientation:(int)orientation;
-(void)_reloadIconViewsAndShowFirstPage:(BOOL)page;
-(void)downloadChanged:(id)changed;
-(void)downloadRemoved:(id)removed;
-(void)viewDidRotateFromInterfaceOrientation:(int)view;
-(void)viewWillAnimateRotationToInterfaceOrientation:(int)view;
-(void)viewWillRotateToInterfaceOrientation:(int)view;
-(void)viewDidDisappear;
-(void)viewWillDisappear;
-(void)viewDidAppear;
-(void)viewWillAppear;
-(float)bottomBarHeight;
-(id)view;
-(void)_newsstandFolderWasOpened:(id)opened;
-(void)_appsDidChange:(id)_apps;
-(void)dealloc;
-(id)init;
@end

