/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBAppSwitcherScrollViewDelegate.h"

@class NSNumber, UIView, SBAppSwitcherScrollView, SBLinenView, NSMutableDictionary, NSMutableArray;
@protocol SBAppSwitcherBarViewDelegate;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherBarView : XXUnknownSuperclass <SBAppSwitcherScrollViewDelegate> {
	id<SBAppSwitcherBarViewDelegate> _delegate;
	NSMutableDictionary* _visibleIconViewMap;
	NSMutableArray* _iconDisplayIDs;
	UIView* _contentView;
	SBLinenView* _backgroundView;
	NSMutableArray* _auxViews;
	SBAppSwitcherScrollView* _scrollView;
	BOOL _animateContentReflow;
	BOOL _animatedScrolling;
	int _reflowIconCount;
	int _lastPageIndex;
	unsigned _firstVisibleIconIndex;
	unsigned _lastVisibleIconIndex;
	BOOL _isVisible;
	BOOL _isEditing;
	CGPoint _savedPositionForSuspendGesture;
	int _orientation;
	NSNumber* _rotatingFromOrientationForFirstLayoutUse;
	BOOL _showFirstPageOnLayout;
	BOOL _rotating;
}
@property(assign, nonatomic, getter=isEditing) BOOL editing;
@property(assign, nonatomic) id<SBAppSwitcherBarViewDelegate> delegate;
+(float)edgePadding:(int)padding;
+(float)edgePaddingForWidth:(float)width;
+(CGSize)viewSize:(int)size;
+(unsigned)iconsPerPage:(int)page;
-(void)viewDidRotateFromInterfaceOrientation:(int)view;
-(void)viewWillAnimateRotationToInterfaceOrientation:(int)view;
-(void)viewWillRotateToInterfaceOrientation:(int)view;
-(void)restoreScrollPositionAfterSuspendGesture;
-(void)saveScrollPositionBeforeSuspendGesture;
-(BOOL)scrollView:(id)view shouldCancelInContentForView:(id)view2;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)_scrollingDidFinish;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)_setAnimatedScrolling:(BOOL)scrolling;
-(void)_commonScrollingWillBegin;
-(void)_reflowAnimationDidStop:(id)_reflowAnimation finished:(id)finished context:(void*)context;
-(void)_layoutIconsInRange:(BOOL)range minIndex:(unsigned)index maxIndex:(unsigned)index3;
-(void)_layoutIconsInVisibleRange:(BOOL)visibleRange;
-(void)_toggleIconViewEditingState:(id)state animated:(BOOL)animated;
-(unsigned)iconIndexColumnOnPageAtPoint:(CGPoint)point orientation:(int)orientation;
-(void)_computeVisibleIconIndexRange:(BOOL)range forOrientation:(int)orientation contentOffset:(CGPoint)offset firstIndex:(unsigned*)index lastIndex:(unsigned*)index5;
-(void)_setVisibleIconIndexRange:(BOOL)range;
-(float)_horizontalBumpForIconIndexOnPage:(unsigned)iconIndexOnPage orientation:(int)orientation;
-(id)_iconViewForIcon:(id)icon creatingIfNecessary:(BOOL)necessary;
-(id)_iconForDisplayIdentifier:(id)displayIdentifier;
-(id)visibleIconViewForDisplayIdentifier:(id)displayIdentifier;
-(int)_pageForIndex:(unsigned)index orientation:(int)orientation;
-(int)_pageForOffset:(CGPoint)offset withSize:(CGSize)size;
-(CGPoint)_firstPageOffset:(CGSize)offset;
-(unsigned)_pageCount:(int)count;
-(CGRect)_iconFrameForIndex:(unsigned)index withSize:(CGSize)size orientation:(int)orientation;
-(void)_positionAtFirstPage:(BOOL)firstPage;
-(void)_adjustScrollContentSize;
-(CGPoint)_newScrollContentOffsetFromOldOffset:(CGPoint)oldOffset oldSize:(CGSize)size oldOrientation:(int)orientation toNewSize:(CGSize)newSize newOrientation:(int)orientation5;
-(void)_adjustContentOffsetForReflow:(BOOL)reflow;
-(BOOL)_isIndexVisible:(unsigned)visible;
-(void)_clearIconViews;
-(void)layoutSubviews;
-(void)didMoveToSuperview;
-(void)viewDidDisappear;
-(void)viewWillDisappear;
-(void)viewWillAppear;
-(BOOL)airPlayControlsVisible;
-(BOOL)nowPlayingControlsVisible;
-(void)addAuxiliaryViews:(id)views;
-(void)reloadOrRemoveIconWithDisplayIdentifier:(id)displayIdentifier;
-(void)_iconRemoveDidStop:(id)_iconRemove finished:(id)finished context:(id)context;
-(void)removeIconWithDisplayIdentifier:(id)displayIdentifier;
-(void)addIconWithDisplayIdentifier:(id)displayIdentifier;
-(BOOL)isVisible;
-(BOOL)isScrolling;
-(id)displayIdentifiers;
-(void)prepareForDisplay:(id)display showFirstPage:(BOOL)page orientation:(int)orientation;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

