/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNewsstandItemIconViewBase.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase {
}
+(Class)_labelImageParametersClassForIcon:(id)icon location:(int)location;
-(id)_superviewForAccessoryView;
-(void)positionIconImageView;
-(void)positionCloseBoxOfType:(int)type;
-(void)_updateLabelVisibility;
-(void)setShadowsHidden:(BOOL)hidden;
-(CGRect)defaultFrameForProgressBar;
-(id)initWithFrame:(CGRect)frame;
@end

