/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppVisibilityPreferences : XXUnknownSuperclass {
	BOOL _defaultVisible;
	BOOL _currentlyVisible;
}
@property(assign) BOOL currentlyVisible;
@property(readonly, assign) BOOL defaultVisible;
-(id)initWithDefaultVisible:(BOOL)defaultVisible;
@end

