/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIFullscreenAnimationViewDelegate.h"
#import "SBUIAnimationController.h"

@class SBAppToAppTransitionView;

__attribute__((visibility("hidden")))
@interface SBAppToAppTransitionController : SBUIAnimationController <SBUIFullscreenAnimationViewDelegate> {
	SBAppToAppTransitionView* _transitionView;
	BOOL _requiresHostView;
	BOOL _dismissBanner;
}
@property(retain, nonatomic) SBAppToAppTransitionView* transitionView;
+(id)_transitionWindow;
-(void)appTransitionViewAnimationDidStop:(id)appTransitionViewAnimation;
-(void)appTransitionView:(id)view animationWillStartWithDuration:(double)animation afterDelay:(double)delay;
-(void)_cleanupAnimation;
-(void)_cancelAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)_setHidden:(BOOL)hidden;
-(id)_animationProgressDependency;
-(BOOL)_animationShouldStart;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
@end

