/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAppSwitcherBarViewDelegate <NSObject>
-(void)appSwitcherBar:(id)bar pageAtIndexDidDisappear:(int)pageAtIndex;
-(void)appSwitcherBar:(id)bar pageAtIndexDidAppear:(int)pageAtIndex;
-(BOOL)appSwitcherBar:(id)bar scrollShouldCancelInContentForView:(id)scroll;
-(void)appSwitcherBarRemovedFromSuperview:(id)superview;
@end

