/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppContextHostManager;

__attribute__((visibility("hidden")))
@interface SBAppContextHostView : XXUnknownSuperclass {
	SBAppContextHostManager* _manager;
}
@property(assign, nonatomic) SBAppContextHostManager* manager;
-(id)window;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)description;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithDefaultSize;
@end

