/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBAppSwitcherScrollViewDelegate;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherScrollView : XXUnknownSuperclass {
}
@property(assign, nonatomic) id<SBAppSwitcherScrollViewDelegate> delegate;
-(BOOL)touchesShouldCancelInContentView:(id)touches;
@end

