/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBApplicationPersistence : XXUnknownSuperclass {
	NSMutableDictionary* _state;
	BOOL _dirty;
	NSObject<OS_dispatch_queue>* _stateQueue;
	NSObject<OS_dispatch_queue>* _writeQueue;
}
+(void)migrateSystemLocalNotifications;
+(id)_statePath;
+(id)sharedInstance;
-(void)_markDirty;
-(void)_flushSynchronously;
-(void)flushSynchronously;
-(void)purgeKeysForBundleAndDisplayIdentifiersOtherThan:(id)bundleAndDisplayIdentifiersOtherThan;
-(id)allBundleOrDisplayIdentifiersWithState;
-(void)setArchivedObject:(id)object forKey:(id)key bundleOrDisplayIdentifier:(id)identifier;
-(id)archivedObjectForKey:(id)key bundleOrDisplayIdentifier:(id)identifier ofType:(Class)type;
-(void)setValue:(id)value forKey:(id)key bundleOrDisplayIdentifier:(id)identifier;
-(id)valueForKey:(id)key bundleOrDisplayIdentifier:(id)identifier ofType:(Class)type;
-(id)init;
@end

