/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherLabel : XXUnknownSuperclass {
	UILabel* _label;
}
@property(assign, nonatomic) BOOL marqueeRunning;
@property(copy, nonatomic) NSString* text;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

