/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"
#import "SpringBoard-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBApplicationIcon : SBLeafIcon {
	NSString* _displayIdentifier;
	unsigned _appIsBeingCleaned : 1;
}
-(id)applicationBundleID;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(void)setBadge:(id)badge;
-(void)launchFromViewSwitcher;
-(void)launch;
-(void)_terminationAssertionDidChange;
-(void)_setAppIsBeingCleanedFlag;
-(BOOL)launchEnabled;
-(id)automationID;
-(id)tags;
-(BOOL)canEllipsizeLabel;
-(id)displayName;
-(id)generateIconImage:(int)image;
-(BOOL)canGenerateImageInBackgroundForFormat:(int)format;
-(void)generateIconImageInBackground:(id)background;
-(id)blockForGeneratingIconImageInBackgroundWithFormat:(int)format;
-(id)_blockForGeneratingIconImageInBackgroundWithFormat:(int)format complete:(id)complete;
-(id)__loadIconImage:(id)image format:(int)format scale:(float)scale;
-(void)completeUninstall;
-(id)application;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithApplication:(id)application;
@end

