/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppWindow : XXUnknownSuperclass {
}
+(CGRect)constrainFrameToScreen:(CGRect)screen;
-(void)becomeKeyWindow;
@end

