/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUIFullscreenAnimationView.h"

@class SBApplication, UIView, CATransformLayer, CALayer;

__attribute__((visibility("hidden")))
@interface SBAppToAppTransitionView : SBUIFullscreenAnimationView {
	SBApplication* _toApplication;
	CATransformLayer* _transformLayer;
	CALayer* _startLayer;
	CALayer* _stopLayer;
	UIView* _fromView;
	UIView* _toView;
	int _orientation;
}
@property(assign, nonatomic) int orientation;
@property(retain, nonatomic) SBApplication* toApp;
-(float)_rotationRadians;
-(id)_rotationValueFunction;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)endTransition;
-(void)beginTransition;
-(void)setToView:(id)view;
-(void)setFromView:(id)view;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

