/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppSwitcherVolumeSlider : XXUnknownSuperclass {
}
-(void)setSliderEnabled:(BOOL)enabled withDuration:(double)duration;
-(UIEdgeInsets)_thumbHitEdgeInsets;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(CGRect)trackRectForBounds:(CGRect)bounds;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end

