/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class BKSApplicationStateMonitor, NSDictionary, NSArray, NSLock, NSMutableDictionary, NSMutableSet, NSOperationQueue, SBApplication, SBDataLookupResults;

@interface SBApplicationController : NSObject
{
    SBDataLookupResults *_pendingDataLookupResults;
    NSLock              *_pendingDataLookupResultsLock;
    NSMutableDictionary *_applications;
    NSMutableDictionary *_applicationsByBundleIdentifer;
    NSMutableSet        *_applicationsPlayingMutedAudioSinceLastLock;
    SBApplication       *_applicationCurrentlyRecordingAudio;
    NSInteger            _locationStatusBarIconType;
    NSDictionary        *_backgroundDisplayDict;
    unsigned int         _ignoreUninstallationEventCount;
    NSOperationQueue    *_backgroundOperationQueue;
    NSLock              *_applicationsLock;
    NSMutableDictionary *_systemAppsVisibilityOverrides;
    NSMutableSet        *_appsToAutoLaunchAfterBoot;
    BKSApplicationStateMonitor *_appStateMonitor;


}
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)arg1;

// Public (to other classes)
- (NSArray *)newsstandApps;
- (NSArray *)webApplications;
- (SBApplication *)mobilePhone;
- (SBApplication *)setupApplication;
- (id)dataActivation;
- (SBApplication *)applicationCurrentlyRecordingAudio;
- (SBApplication *)iPod;
- (SBApplication *)applicationWithPid:(int)arg1;
- (SBApplication *)applicationWithDisplayIdentifier:(id)arg1;
- (NSArray *)applicationsWithPid:(int)arg1;
- (NSArray *)applicationsWithBundleIdentifier:(id)arg1;
- (NSArray *)allApplications;
- (NSArray *)allDisplayIdentifiers;
- (void)autoLaunchAppsIfNecessaryAfterBoot;
- (int)locationStatusBarIconType; // 0 = no icon, 1 = Geofence, 2 = Normal Location Tracking
- (void)buildLocationState;
- (void)queuePendingDataLookupResults:(id)arg1;
- (id)dequeuePendingDataLookupResults;
- (BOOL)hasPendingDataLookupResults;
- (BOOL)updateAppIconVisibilityOverridesShowing:(id *)arg1 hiding:(id *)arg2;
- (int)appVisibilityOverrideForBundleIdentifier:(id)arg1;
- (void)processPendingInstalls;
- (void)loadApplicationsWithBundle:(id)arg1 bundlePath:(id)arg2 isSystemApplication:(BOOL)arg3 defaultTags:(id)arg4 signerIdentity:(id)arg5 provisioningProfileValidated:(BOOL)arg6 seatbeltEnvironmentVariables:(id)arg7;
- (Class)applicationClassForInfoDictionary:(id)arg1;
- (void)loadWebclipAndIcon:(id)arg1;
- (void)loadApplicationsAndIcons:(id)arg1 reveal:(BOOL)arg2 popIn:(BOOL)arg3;
- (void)waitForOperationsToComplete;
- (void)uninstallApplication:(SBApplication *)app;
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)arg1;
- (BOOL)loadApplication:(SBApplication *)app    ;
- (id)loadApplications;

// Internal methods
- (void)_setVisibilityOverridesAreDirty:(BOOL)arg1;
- (void)_reloadBackgroundIDsDict;
- (void)_handleDataLookupResultsIfReceived;
- (void)_applicationRegistrationChangedCallback:(id)arg1 info:(id)arg2;
- (void)_applicationsUnregistered:(NSArray *)arg1;
- (void)_applicationsRegistered:(id)arg1;
- (void)_applicationsRegistered:(id)arg1 unregistered:(id)arg2;
- (BOOL)_hasRequiredCapabilities:(id)arg1;
- (void)_loadApplicationsAndIcons:(id)arg1 removed:(id)arg2 applicationDictionaries:(id)arg3 reveal:(BOOL)arg4 popIn:(BOOL)arg5 reloadAllIcons:(BOOL)arg6;
- (void)_updateIconControllerAndModelForLoadedApplications:(id)arg1 reveal:(BOOL)arg2 popIn:(BOOL)arg3 reloadAllIcons:(BOOL)arg4;
- (void)_decrementUninstallationEventCount;
- (id)_loadApplications:(BOOL)arg1 applicationDictionaries:(id)arg2;
- (id)_loadApplications:(id)arg1 removed:(id)arg2 applicationDictionaries:(id)arg3 updateRestrictions:(BOOL)arg4;
- (void)_calculateApplicationDiff:(id *)arg1 removed:(id *)arg2 applicationDictionaries:(id)arg3;
- (id)_modifiedApplications:(id)arg1 applicationDictionaries:(id)arg2;
- (BOOL)_applicationHasBeenModified:(id)arg1 applicationDictionary:(id)arg2;
- (void)_loadApplication:(SBApplication *)arg1 dictionary:(NSDictionary *)arg2 allowDemoOnly:(BOOL)arg3;
- (void)_loadApplication:(SBApplication *)arg1 dictionary:(NSDictionary *)arg2;
- (void)_postLoadApplications:(NSArray *)arg1 removed:(NSArray *)arg2 modified:(NSArray *)arg3 updateRestrictions:(BOOL)arg4;
- (void)_sendInstalledAppsDidChangeNotification:(id)arg1 removed:(id)arg2 modified:(id)arg3;
- (void)_preLoadApplications;
- (void)_updateLocationState;
- (void)_memoryWarningReceived;
- (void)_lockStateChanged:(id)arg1;
- (void)_unusuallyMutedAudioPlaying:(id)arg1;
- (void)_recordingStateChanged:(id)arg1;
- (void)_mediaServerConnectionDied:(id)arg1;
- (void)_registerForAVSystemControllerNotifications;
- (void)_unregisterForAVSystemControllerNotifications;

@end
