/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet;

__attribute__((visibility("hidden")))
@interface SBApplicationDataLookupOperation : XXUnknownSuperclass {
	NSSet* _registeredBundleIDs;
	NSSet* _unregisteredBundleIDs;
}
-(void)main;
-(void)dealloc;
-(id)initWithRegisteredBundleIDs:(id)registeredBundleIDs unregisteredBundleIDs:(id)ids;
@end

