/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAppToAppTransitionView.h"


__attribute__((visibility("hidden")))
@interface SBAppDosadoView : SBAppToAppTransitionView {
}
-(void)endTransition;
-(void)beginTransition;
@end

