/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBHomeCentricPopoverControllerDelegate.h"
#import "SBShowcaseViewControllerProtocol.h"
#import "SBUIPluginHost.h"

@class SBDeviceLockDisableAssertion, SBShowcaseController, NSString, SBHomeCentricPopoverController;

__attribute__((visibility("hidden")))
@interface SBAssistantController : SBUIPluginHost <SBHomeCentricPopoverControllerDelegate, SBShowcaseViewControllerProtocol> {
	SBHomeCentricPopoverController* _homeCentricPopover;
	NSString* _popoverAppDisplayIDBeingHosted;
	SBShowcaseController* _showcase;
	int _revealMode;
	BOOL _unlockedDevice;
	BOOL _isDismissing;
	int _activationEvent;
	SBDeviceLockDisableAssertion* _disableAssertion;
}
@property(assign, nonatomic) int revealMode;
@property(assign, nonatomic) SBShowcaseController* showcase;
@property(assign, getter=isDismissing) BOOL dismissing;
@property(assign, nonatomic) BOOL unlockedDevice;
+(BOOL)_runActivateAssistantTest;
+(BOOL)isAssistantRunningHidden;
+(BOOL)isAssistantVisible;
+(BOOL)shouldEnterAssistant;
+(BOOL)supportedAndEnabled;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
-(void)uiPlugin:(id)plugin ignoresKeyboardAvoidance:(BOOL)avoidance;
-(void)uiPlugin:(id)plugin forceUpdateToInterfaceOrientation:(int)interfaceOrientation animated:(BOOL)animated;
-(void)uiPlugin:(id)plugin isNowRunning:(BOOL)running;
-(void)uiPluginUserEventOccurred:(id)occurred;
-(BOOL)uiPlugin:(id)plugin openURL:(id)url;
-(BOOL)uiPlugin:(id)plugin launchApplicationWithBundleID:(id)bundleID openURL:(id)url;
-(BOOL)uiPluginAttemptDeviceUnlock:(id)unlock withPassword:(id)password lockViewOwner:(id)owner;
-(void)uiPluginWantsSizeUpdate:(id)update revealMode:(int)mode withBlock:(id)block;
-(BOOL)uiPluginWantsActivation:(id)activation forEvent:(int)event revealMode:(int)mode completion:(id)completion;
-(void)_presentPopover:(id)popover revealMode:(int)mode completion:(id)completion;
-(int)_showcaseRevealModeForPluginRevealMode:(int)pluginRevealMode;
-(void)revealModeWillChange:(int)revealMode;
-(void)_dismissUIPlugin:(id)plugin animated:(BOOL)animated;
-(BOOL)pluginSuppressesNotifications;
-(BOOL)pluginWantsScreenDimInterval:(double*)interval;
-(BOOL)pluginWantsInterfaceOrientation:(int*)orientation;
-(void)preparePluginForActivationEvent:(int)activationEvent afterInterval:(double)interval;
-(BOOL)pluginWantsActivationEvent:(int)event interval:(double*)interval;
-(void)homeCentricPopoverDidDismissView:(id)homeCentricPopover;
-(void)homeCentricPopoverWillDismissView:(id)homeCentricPopover animated:(BOOL)animated;
-(void)homeCentricPopoverDidPresentView:(id)homeCentricPopover;
-(void)homeCentricPopoverWillPresentView:(id)homeCentricPopover animated:(BOOL)animated;
-(void)_cleanupContextHosting;
-(BOOL)activateIgnoringTouches;
-(float)revealAmountForMode:(int)mode;
-(float)bottomBarHeight;
-(BOOL)shouldShowLockStatusBarTime;
-(BOOL)_isPluginLoaded;
-(void)_loadPlugin;
-(void)dismissAssistantForAlertActivation:(id)alertActivation;
-(void)dismissAssistantWithFadeOfDuration:(double)duration;
-(void)dismissAssistantWithFade;
-(void)dismissAssistant;
-(void)_notePluginVisibilityDidChange;
-(void)viewDidDisappear;
-(void)viewDidAppear;
-(void)dealloc;
-(id)init;
@end

