/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAutoPurgingImageView : XXUnknownSuperclass {
	id _block;
}
-(void)setImage:(id)image;
-(void)didMoveToWindow;
-(void)dealloc;
-(id)initWithImageNamed:(id)imageNamed;
-(id)_initWithImageBlock:(id)imageBlock andInitialLoadBlock:(id)block;
@end

