/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, UIImageView;

__attribute__((visibility("hidden")))
@interface SBAwayBuddyBackgroundView : XXUnknownSuperclass {
	UIImageView* _titleView;
	UIButton* _infoButton;
}
-(void)setInfoButtonAlpha:(float)alpha;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

