/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAwayBulletinFloatingCell.h"


__attribute__((visibility("hidden")))
@interface SBAwayCardItemFloatingCell : SBAwayBulletinFloatingCell {
}
-(void)lockBarUnlocked:(id)unlocked;
@end

