/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIImage, TPLCDView, NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface SBAwayInCallController : XXUnknownSuperclass {
	TPLCDView* _lcdView;
	BOOL _shouldShowInCallInfo;
	BOOL _isShowingInCallInfo;
	NSTimer* _durationTimer;
	CTCallRef _displayedCall;
	NSString* _localizedLabel;
	UIImage* _callerImage;
	BOOL _isFullScreen;
}
-(void)_setShowingInCallInfo:(BOOL)callInfo;
-(BOOL)isShowingInCallInfo;
-(void)setShouldShowInCallInfo:(BOOL)showInCallInfo;
-(void)reload;
-(void)updateDuration;
-(void)fetchCallInformation:(id*)information name:(id*)name label:(id*)label image:(id*)image isFullScreen:(BOOL*)screen wantsHighResolution:(BOOL)resolution;
-(BOOL)callerImageIsFullScreen;
-(id)callerImage;
-(void)dealloc;
-(id)initWithLCDView:(id)lcdview;
@end

