/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UITableView, UIImageView;
@protocol SBAwayBulletinListViewDelegate;

__attribute__((visibility("hidden")))
@interface SBAwayBulletinListView : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
	UITableView* _tableView;
	UIView* _tableContainerView;
	UIView* _tableBackgroundView;
	UIView* _tableTopFadeOverlay;
	UIView* _tableBottomFadeOverlay;
	UIView* _tableFadeMaskContainer;
	UIImageView* _grabberFadeMaskImageView;
	UIView* _tableHeaderView;
	UIView* _tableFooterView;
	UIView* _dropShadowView;
	UITableView* _firstAlertTableView;
	UIView* _firstAlertBGView;
	float _firstAlertTableHeight;
	UIView* _tableGrabberView;
	int _normalViewStyle;
	float _normalTableHeight;
	id<SBAwayBulletinListViewDelegate> _delegate;
	int _viewStyle;
	BOOL _hiddenForUnlock;
	BOOL _shouldShowFirstAlertTable;
	BOOL _animatingGrabEnded;
	BOOL _grabberGrabbed;
}
@property(assign, nonatomic) id<SBAwayBulletinListViewDelegate> delegate;
@property(readonly, assign, nonatomic) UITableView* firstAlertTableView;
@property(readonly, assign, nonatomic) int viewStyle;
@property(readonly, assign, nonatomic) UITableView* tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(CGRect)_grabberHitFrame;
-(void)_grabEndedWithVelocity:(CGPoint)velocity cancelled:(BOOL)cancelled;
-(void)_grabEndedWithVelocity:(CGPoint)velocity cancelled:(BOOL)cancelled animated:(BOOL)animated;
-(void)_updateForGrabBeganOrMovedWithLocation:(CGPoint)location velocity:(CGPoint)velocity;
-(void)handleGrabberPan:(id)pan;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(id)_tableFooterView;
-(id)_tableHeaderView;
-(void)clearFloatingAlertButtonHandler;
-(BOOL)floatingAlertNeedsMainUnlockAction;
-(void)setFirstAlertTableHeight:(float)height;
-(void)setFirstAlertTableViewHidden:(BOOL)hidden;
-(void)layoutSubviews;
-(void)lockBarStoppedTracking;
-(void)lockBarStartedTracking;
-(float)floatingTableContainerHeightForContentHeight:(float)contentHeight;
-(void)setHiddenForUnlock:(BOOL)unlock force:(BOOL)force;
-(BOOL)wantsToHideTopBarShadowView;
-(BOOL)isHiddenForUnlock;
-(BOOL)shouldHideBySlidingOut;
-(void)_slideOutTransforms:(CGAffineTransform*)transforms grabberTransform:(CGAffineTransform*)transform;
-(BOOL)hasShownNotificationsManually;
-(BOOL)shouldAutoHideNotifications;
-(void)setViewStyle:(int)style withFloatingAlert:(BOOL)floatingAlert andTableHeight:(float)height force:(BOOL)force;
-(void)setViewStyle:(int)style withFloatingAlert:(BOOL)floatingAlert andTableHeight:(float)height;
-(BOOL)shouldOverrideToSlideUpStyle:(BOOL)slideUpStyle;
-(float)_tableContainerViewAlphaForSlideUp;
-(float)_translationDistanceForGrabber;
-(CGSize)_maxPinnedContainerSize;
-(void)setFrame:(CGRect)frame;
-(void)_setupHierarchyIfNecessaryWithStyle:(int)style;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate style:(int)style;
@end

