/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBSCardItem;

__attribute__((visibility("hidden")))
@interface SBAwayCardListItem : XXUnknownSuperclass {
	SBSCardItem* _cardItem;
}
@property(copy, nonatomic) SBSCardItem* cardItem;
-(BOOL)inertWhenLocked;
-(id)sortDate;
-(void)dealloc;
@end

