/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAwayDateViewDelegate <NSObject>
@optional
-(void)awayDateViewDidChangeTitle:(id)awayDateView;
@end

