/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAwayBulletinCell.h"


__attribute__((visibility("hidden")))
@interface SBAwayBulletinFloatingCell : SBAwayBulletinCell {
	BOOL _hideIcon;
}
+(float)_cellContentExtraPadding;
+(float)_cellContentTopPadding;
+(float)_cellContentRightPadding;
+(float)_cellContentLeftPadding;
+(float)_cellIconLeftPadding;
+(float)rowHeightForSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines attachmentText:(id)text imageSize:(CGSize)size rowWidth:(float)width;
+(float)rowHeightForSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines rowWidth:(float)width;
+(float)_rowHeightForContentHeight:(float)contentHeight;
+(float)_contentWidthForRowWidth:(float)rowWidth leaveRoomForIcon:(BOOL)icon;
-(BOOL)_createsLockBarEarly;
-(void)layoutSubviews;
-(CGRect)_cellContentViewFrame;
-(CGRect)_contentRect;
-(BOOL)_drawsSeparator;
-(id)_lockBar;
-(void)setUnlockActionContext:(id)context;
-(void)setAttachmentImage:(id)image;
-(BOOL)_hasBackgroundColor;
-(void)_createContentView;
@end

