/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinCellContentViewBase.h"


__attribute__((visibility("hidden")))
@interface SBAwayBulletinFloatingContentView : SBBulletinCellContentViewBase {
	BOOL _hasButton;
}
@property(assign, nonatomic) BOOL hasButton;
+(float)heightForSystemAlertStyleWithTitle:(id)title maxLines:(unsigned)lines message:(id)message maxLines:(unsigned)lines4 buttonHeight:(float)height contentWidth:(float)width;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines attachmentText:(id)text imageHeight:(float)height contentWidth:(float)width;
+(float)heightForBulletinStyleWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines contentWidth:(float)width;
-(void)_configureLabel:(id)label withFont:(id)font color:(id)color alignment:(int)alignment;
-(void)layoutSubviews;
-(void)setAttachmentText:(id)text;
-(void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;
-(void)setMessage:(id)message;
-(void)setSubtitle:(id)subtitle;
-(void)setTitle:(id)title;
-(id)_vipAccessoryImage;
-(id)_dateFont;
-(id)_attachmentFont;
-(id)_messageFont;
-(id)_subtitleFont;
-(id)_titleFont;
@end

