/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAwayBulletinCell.h"


__attribute__((visibility("hidden")))
@interface SBAwayCardItemCell : SBAwayBulletinCell {
}
-(void)lockBarUnlocked:(id)unlocked;
@end

