/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAwayBulletinListViewDelegate <NSObject>
@optional
-(void)sliderGrabDidEnd;
-(void)sliderGrabWillEnd:(BOOL)sliderGrab;
-(void)willSetViewStyle:(int)style;
-(BOOL)hasShownNotificationsManually;
-(BOOL)shouldAutoHideNotifications;
@end

