/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import "SBBulletinWindowClient.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinBusyClient.h"
#import "SBUIBannerSourceManager.h"

@class UIView, NSMutableSet, NSMutableArray, SBBannerDismissOverdueContext, SBBannerAndShadowView;

__attribute__((visibility("hidden")))
@interface SBBannerController : XXUnknownSuperclass <SBUIBannerSourceManager, SBBulletinWindowClient, SBBulletinBusyClient, UIGestureRecognizerDelegate> {
	NSMutableSet* _sources;
	NSMutableArray* _pendingStickyBannerItems;
	SBBannerAndShadowView* _bannerAndShadowView;
	UIView* _snapshotViewForAssistantShrinkFromFull;
	UIView* _snapshotView;
	BOOL _soundIsPlaying;
	BOOL _dismissalOverdue;
	BOOL _replaceDelayIsActive;
	BOOL _showingStickyDurationBanner;
	BOOL _suppressingBanners;
	BOOL _enableDelayActive;
	BOOL _assistantIsFullyVisible;
	BOOL _bannerPanGestureInProgress;
	float _showcaseHeight;
	id _animationContext;
	id _dismissOverdueContext;
}
@property(retain, nonatomic) SBBannerDismissOverdueContext* dismissOverdueContext;
@property(retain, nonatomic) UIView* snapshotViewForAssistantShrinkFromFull;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(id)_meshTransformForDegreesOfRotation:(float)rotation flipInsets:(UIEdgeInsets)insets orientation:(int)orientation topIsLive:(BOOL)live;
-(void)_removePerspective;
-(void)_setUpPerspectiveForNormalFlipRect:(CGRect)normalFlipRect;
-(CGRect)_calculateFlipRectAndCreateSnapshotViewForBannerFrame:(CGRect)bannerFrame orientation:(int)orientation;
-(CGRect)_currentBannerFrameForOrientation:(int)orientation;
-(CGRect)_normalBannerFrameForOrientation:(int)orientation;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)_flipWithContext:(id)context;
-(void)_soundDidFinishPlayingForBannerItem:(id)_sound;
-(void)_dismissOverdueOrDequeueIfPossible;
-(void)_stopCurrentSound;
-(void)_replaceIntervalElapsed;
-(void)_dismissIntervalElapsed;
-(void)_sendDismissCallbacksIfNecessary:(int)necessary;
-(void)_tryToDismissBannerWithContext:(id)context;
-(void)_tryToDismissBannerWithAnimation:(int)animation;
-(void)_tryToDismissBannerWithAnimation:(int)animation dismissReason:(int)reason;
-(void)_handleBannerTapGesture:(id)gesture;
-(void)_handleBannerPanGesture:(id)gesture;
-(void)_adjustShadowAlphasForProgress:(float)progress;
-(float)_progressForBannerTranslation:(float)bannerTranslation maxTranslation:(float)translation;
-(void)_setBannerTranslation:(float)translation progress:(float)progress;
-(BOOL)_presentBannerForItem:(id)item existingDismissReason:(int)reason;
-(void)_presentBannerView:(id)view dismissReason:(int)reason;
-(void)_presentBannerView:(id)view;
-(void)_tearDownView:(BOOL)view reason:(int)reason;
-(void)_tearDownView;
-(BOOL)_shouldPendStickyBannerItem:(id)item withReason:(int)reason;
-(BOOL)_dequeueBannerIfPossibleIgnoringStickyBanner:(BOOL)banner existingDismissReason:(int)reason;
-(BOOL)_dequeueBannerIfPossibleIgnoringStickyBanner:(BOOL)banner;
-(BOOL)_dequeueBannerIfPossible;
-(BOOL)_canDequeueIgnoringStickyBanner:(BOOL)banner;
-(BOOL)_canDequeue;
-(id)_dequeueNextBannerItem;
-(BOOL)_isItemShowable:(id)showable;
-(id)_animationContext;
-(void)_dequeueAfterDelayIfPossible;
-(void)_updateBannerSuppressionStateAndDequeueIfPossible:(BOOL)possible withDelay:(BOOL)delay;
-(void)_updateBannerSuppressionState;
-(void)_removePendingStickyItemsForSource:(id)source;
-(id)_pendingStickyBannerItemForSource:(id)source;
-(void)assistantRevealModeDidChange:(id)assistantRevealMode;
-(void)assistantRevealModeWillChange:(id)assistantRevealMode;
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
-(void)bulletinWindowStoppedBeingBusy;
-(void)dismissCurrentBannerItemForSource:(id)source;
-(id)currentBannerItemForSource:(id)source;
-(void)signalSource:(id)source;
-(void)unregisterSource:(id)source;
-(void)registerSource:(id)source;
-(void)adjustLayoutForShowcaseHeight:(float)showcaseHeight;
-(id)newBannerSnapshotViewRotatedForOrientation:(int)orientation;
-(void)setBannerAlpha:(float)alpha;
-(void)dismissBannerWithAnimation:(int)animation reason:(int)reason;
-(void)dismissBannerWithoutAnimationForReason:(int)reason;
-(id)currentBannerItem;
-(BOOL)isShowingBanner;
-(void)dealloc;
-(id)init;
@end

