/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBannerDismissOverdueContext : XXUnknownSuperclass {
	int _dismissReason;
}
@property(assign, nonatomic) int dismissReason;
+(id)dismissOverdueContextWithReason:(int)reason;
@end

