/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBBatteryReflectionView : XXUnknownSuperclass {
	UIImage* _image;
	UIImage* _maskImage;
	float _bottomMargin;
}
-(void)drawRect:(CGRect)rect;
-(void)setImage:(id)image;
-(void)dealloc;
-(id)initWithImage:(id)image bottomMargin:(float)margin;
@end

