/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"
#import "SpringBoard-Structs.h"

@class UIWebClip;

__attribute__((visibility("hidden")))
@interface SBBookmarkIcon : SBLeafIcon {
	UIWebClip* _webClip;
}
@property(retain, nonatomic) UIWebClip* webClip;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(void)completeUninstall;
-(void)launch;
-(id)displayName;
-(id)generateIconImage:(int)image;
-(BOOL)allowsUninstall;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithWebClip:(id)webClip;
@end

