/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BBSettingsGateway, BBSystemStateProvider;

__attribute__((visibility("hidden")))
@interface SBBulletinSystemStateAdapter : XXUnknownSuperclass {
	BBSystemStateProvider* _stateProvider;
	BBSettingsGateway* _settingsGateway;
	BOOL _quietModeEnabled;
}
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
-(void)_lostModeStateChanged;
-(void)_screenDimmed:(id)dimmed;
-(void)_lockStateChanged:(id)changed;
-(BOOL)quietModeEnabled;
-(void)_activeBehaviorOverrideTypesChanged:(unsigned)changed;
-(void)dealloc;
-(id)init;
@end

