/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSMutableArray, NSString, NSDate, NSArray, SBWeeApp;

__attribute__((visibility("hidden")))
@interface SBBulletinListSection : XXUnknownSuperclass {
	NSString* _sectionID;
	unsigned _sectionType;
	SBWeeApp* _weeApp;
	NSMutableArray* _bulletins;
	NSArray* _sortDescriptors;
	NSString* _displayName;
	UIImage* _iconImage;
	BOOL _displaysCriticalBulletins;
	NSDate* _lastSortDate;
}
@property(retain, nonatomic) UIImage* iconImage;
@property(copy, nonatomic) NSString* displayName;
@property(retain, nonatomic) NSArray* sortDescriptors;
@property(retain, nonatomic) SBWeeApp* weeApp;
@property(copy, nonatomic) NSString* sectionID;
-(id)bulletinAtIndex:(unsigned)index;
-(unsigned)replaceBulletin:(id)bulletin withBulletin:(id)bulletin2;
-(unsigned)removeBulletin:(id)bulletin;
-(unsigned)_removeBulletin:(id)bulletin;
-(unsigned)addBulletin:(id)bulletin;
-(unsigned)indexOfBulletinID:(id)bulletinID;
-(unsigned)_indexForNewBulletin:(id)newBulletin;
-(int)compareSection:(id)section forOrder:(unsigned)order;
-(int)compare:(id)compare;
-(void)dealloc;
-(id)initWithSectionInfo:(id)sectionInfo;
-(BOOL)showsTodaysDate;
-(BOOL)displaysCriticalBulletins;
-(id)lastSortDate;
-(BOOL)hasClearableBulletins;
-(unsigned)bulletinCount;
-(BOOL)isBulletinSection;
-(BOOL)isWeeAppSection;
-(id)description;
@end

