/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIGestureRecognizerDelegate.h"


__attribute__((visibility("hidden")))
@interface SBBulletinListTouchEater : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
}
-(BOOL)canBePreventedByGestureRecognizer:(id)recognizer;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
@end

