/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CALayer;

__attribute__((visibility("hidden")))
@interface SBBuddyLogoZoomView : XXUnknownSuperclass {
	CALayer* _contentLayer;
	id _animationCompleteBlock;
}
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)startAnimationWithCompletionBlock:(id)completionBlock;
-(id)initWithFrame:(CGRect)frame;
@end

