/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinImageView.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface SBBulletinLinenSegmentView : SBBulletinImageView {
	UIView* _linenView;
	CGSize _linenSize;
	BOOL _showsLinen;
	SBBulletinImageView* _gradientView;
}
@property(assign, nonatomic) BOOL showsLinen;
-(void)didMoveToWindow;
-(void)setFrame:(CGRect)frame;
-(void)setGradientAlpha:(float)alpha;
-(void)adjustContents;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
@end

