/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBBulletinTableView, SBBulletinListTouchEater, SBWeeAppPresentationView, SBLinenFadeContainer, UIView, UIStatusBar, SBBulletinBlurredShadowLabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinListView : XXUnknownSuperclass {
	int _orientation;
	float _currentY;
	UIView* _slidingView;
	UIImageView* _linenView;
	UIView* _linenContainer;
	CGSize _linenSize;
	SBBulletinTableView* _tableView;
	SBLinenFadeContainer* _tableContainer;
	UIStatusBar* _statusBar;
	UIView* _statusBarPocket;
	UIView* _grabber;
	SBWeeAppPresentationView* _presentationView;
	SBBulletinBlurredShadowLabel* _noNotificationsLabel;
	SBBulletinListTouchEater* _clearButtonTouchEater;
	UIView* _cornerView[4];
	UIView* _bottomShadowView;
	UIView* _linenGradient;
	UIView* _linenRim;
	UIView* _wholeShadowView;
	UIView* _sideShadowView[2];
	float _contentHeight;
}
+(id)linen;
+(void)load;
-(void)presentWeeApp:(id)app animateWithDuration:(float)duration delay:(float)delay completion:(id)completion;
-(id)presentingWeeApp;
-(void)_removePresentingWeeAppWithDuration:(float)duration delay:(float)delay completion:(id)completion;
-(void)_presentWeeApp:(id)app duration:(float)duration delay:(float)delay completion:(id)completion;
-(void)_removePresentationView;
-(void)didRotateFromOrientation:(int)orientation;
-(void)willRotateToOrientation:(int)orientation;
-(void)adjustLayoutForTableViewReload;
-(void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)animatedTableViewContentHeightChange duration:(float)duration delay:(float)delay;
-(void)adjustLayoutForAnimatedTableViewContentHeightChange:(float)animatedTableViewContentHeightChange;
-(float)_linenGradientAlphaForHeight:(float)height;
-(float)_iPadSlidingViewHeightInOrientation:(int)orientation;
-(void)_ensureContentHeightHasBeenComputed;
-(void)layoutForOrientation:(int)orientation;
-(void)handleTableViewOffsetChange;
-(float)_pocketAlphaForTableViewOffset;
-(void)handleStatusBarTap:(id)tap;
-(id)clearButtonTouchEater;
-(id)slidingView;
-(CGRect)slidingViewFrame;
-(void)setShowsNoNotificationsLabel:(BOOL)label animated:(BOOL)animated;
-(void)_positionNoNotificationsLabel;
-(void)setBottomShadowAlpha:(float)alpha;
-(void)setCornerAlpha:(float)alpha;
-(void)setBottomCornersOffscreen:(BOOL)offscreen animated:(BOOL)animated;
-(float)currentY;
-(float)offscreenY;
-(float)onscreenY;
-(void)positionSlidingViewAtY:(float)y;
-(id)activeContentView;
-(float)linenGradientAlpha;
-(id)linenView;
-(id)tableView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame delegate:(id)delegate;
@end

