/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinLinenSegmentView.h"
#import "SBBulletinClearButtonDelegate.h"

@class SBBulletinClearButton, NSString, UIView, SBBulletinBlurredShadowLabel;
@protocol SBBulletinHeaderViewDelegate;

__attribute__((visibility("hidden")))
@interface SBBulletinHeaderView : SBBulletinLinenSegmentView <SBBulletinClearButtonDelegate> {
	UIView* _translucentOverlay;
	UIView* _iconView;
	SBBulletinBlurredShadowLabel* _sectionLabel;
	SBBulletinBlurredShadowLabel* _sectionAltLabel;
	SBBulletinClearButton* _clearButton;
	id<SBBulletinHeaderViewDelegate> _delegate;
	NSString* _sectionID;
}
@property(readonly, assign, nonatomic) SBBulletinClearButton* clearButton;
@property(readonly, assign, nonatomic) NSString* sectionID;
@property(assign, nonatomic) id<SBBulletinHeaderViewDelegate> delegate;
+(float)headerHeight;
-(void)willMoveToWindow:(id)window;
-(void)layoutSubviews;
-(void)_dateOrLocaleChanged:(id)changed;
-(CGRect)_positionAltLabel;
-(BOOL)_configureAltTextInAvailableWidth:(float)availableWidth;
-(BOOL)_showingAltLabel;
-(void)setShowsClearButton:(BOOL)button animated:(BOOL)animated;
-(void)clearButton:(id)button willTransitionWithDuration:(double)duration;
-(void)clearButtonWasPressed:(id)pressed;
-(void)dealloc;
-(void)configureWithSection:(id)section;
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
@end

