/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinCellSelectionView : XXUnknownSuperclass {
	UIImageView* _gradientView;
	float _cellSeparatorHeight;
}
-(void)layoutSubviews;
-(void)setCellSeparatorHeight:(float)height;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

