/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinAlertHandler.h"
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"

@class BBObserver, NSMutableArray, NSMapTable, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBBulletinModalController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinAlertHandler, SBBulletinBusyClient> {
	BBObserver* _observer;
	BOOL _deviceIsLocked;
	NSMutableArray* _incomingBulletinEventQueue;
	NSMutableDictionary* _handlersBySectionID;
	NSMapTable* _handlersByBulletinID;
	NSMapTable* _alertsByBulletinID;
}
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
-(void)handleEvent:(int)event withBulletin:(id)bulletin forRegistry:(id)registry;
-(BOOL)bindBulletin:(id)bulletin forRegistry:(id)registry;
-(void)bulletinWindowStoppedBeingBusy;
-(void)observer:(id)observer purgeReferencesToBulletinID:(id)bulletinID;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(BOOL)_enqueueEventBlock:(id)block;
-(void)_dequeuePendedEventsIfPossible;
-(void)_configureBBObserver;
-(id)init;
-(void)destroyingAlert:(id)alert withBulletinID:(id)bulletinID;
@end

