/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBulletinAlertHandlerRegistry.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@protocol SBBulletinAlertHandlerRegistry
-(void)addAlertHandler:(id)handler forSection:(id)section;
@end

__attribute__((visibility("hidden")))
@interface SBBulletinAlertHandlerRegistry : XXUnknownSuperclass <SBBulletinAlertHandlerRegistry> {
	NSMutableDictionary* _handlersBySectionID;
}
-(void)addAlertHandler:(id)handler forSection:(id)section;
-(id)alertHandlersForSection:(id)section;
-(void)dealloc;
-(id)init;
@end

