/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinHeaderViewDelegate <NSObject>
-(void)headerViewWillDisappear:(id)headerView;
-(void)headerViewWillAppear:(id)headerView;
@end

