/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIActiveOrientationObserver.h"

@class NSMutableSet, UIWindow;

__attribute__((visibility("hidden")))
@interface SBBulletinWindowController : XXUnknownSuperclass <SBUIActiveOrientationObserver> {
	UIWindow* _bulletinWindow;
	int _trueBulletinWindowOrientation;
	int _overrideBulletinWindowOrientation;
	BOOL _rotatingKeyboard;
	BOOL _aboveShowcase;
	NSMutableSet* _windowClients;
	NSMutableSet* _keyClients;
	NSMutableSet* _busyClients;
	NSMutableSet* _busyReasons;
}
@property(assign, nonatomic, getter=isWindowAboveShowcase) BOOL windowAboveShowcase;
@property(readonly, assign, nonatomic) UIWindow* window;
+(BOOL)shouldSuppressAlertForBulletin:(id)bulletin;
+(id)sharedInstance;
-(BOOL)_hasKeyWindowClients;
-(void)activeInterfaceOrientationDidChangeToOrientation:(int)activeInterfaceOrientation willAnimateWithDuration:(double)duration fromOrientation:(int)orientation;
-(void)activeInterfaceOrientationWillChangeToOrientation:(int)activeInterfaceOrientation;
-(void)_setTrueWindowOrientation:(int)orientation;
-(void)_setOverrideWindowOrientation:(int)orientation;
-(void)_cleanUpAfterRotatingFromOrientation:(int)orientation;
-(void)_doRotationToOrientation:(int)orientation duration:(double)duration forOverride:(BOOL)override;
-(void)_prepareToRotateToOrientation:(int)orientation forOverride:(BOOL)override;
-(void)clearOverrideWindowOrientation;
-(BOOL)_hasOrientationOverride;
-(void)overrideWindowOrientation:(int)orientation;
-(void)updateBulletinWindowOrientation;
-(int)windowOrientationWithoutOverrides;
-(int)windowOrientation;
-(void)removeBusyClient:(id)client;
-(void)addBusyClient:(id)client;
-(void)removeWindowClient:(id)client;
-(void)_updateWindowTransformAndFrameForOrientation;
-(void)addWindowClient:(id)client;
-(void)_didResignKeyWindow:(id)window;
-(void)_didBecomeKeyWindow:(id)window;
-(void)_resignAsKeyWindow;
-(void)_becomeKeyWindow;
-(BOOL)allowsDismissBannerGesture;
-(BOOL)allowsHideNotificationsGesture;
-(BOOL)allowsShowNotificationsGesture;
-(BOOL)allowsShowNotificationsGestureFromBanner;
-(BOOL)_allowsShowNotificationsGestureFromBanner:(BOOL)banner;
-(BOOL)_isBusyForReason:(id)reason;
-(BOOL)isBusy;
-(void)_assignWindowLevel;
-(void)setBusy:(BOOL)busy forReason:(id)reason;
-(void)dealloc;
-(id)init;
@end

