/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBulletinImageView : XXUnknownSuperclass {
}
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

