/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinClearButtonDelegate <NSObject>
-(void)clearButton:(id)button willTransitionWithDuration:(double)duration;
-(void)clearButtonWasPressed:(id)pressed;
@end

