/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBulletinBlurredShadowLabel : XXUnknownSuperclass {
}
-(void)drawTextInRect:(CGRect)rect;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

