/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinLinenBackedCell.h"

@class SBBulletinCellContentView, UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinListCell : SBBulletinLinenBackedCell {
	UIImageView* _bulletinAccessoryView;
	UIImageView* _bottomCellSeparator;
	SBBulletinCellContentView* _cellContentView;
}
+(float)heightForRowWithSubtitle:(id)subtitle imageHeight:(float)height;
+(float)heightForRowWithSubtitle:(id)subtitle message:(id)message maxLines:(unsigned)lines width:(float)width;
-(void)layoutSubviews;
-(void)setCellSeparatorStyle:(int)style;
-(void)setBulletinAccessoryStyle:(int)style;
-(void)setAttachmentText:(id)text;
-(void)setAttachmentImageSize:(CGSize)size;
-(void)setAttachmentImage:(id)image;
-(void)setStartDate:(id)date endDate:(id)date2 timeZone:(id)zone allDay:(BOOL)day formatStyle:(int)style;
-(void)setMessage:(id)message;
-(void)setSubtitle:(id)subtitle;
-(void)setTitle:(id)title;
-(void)setMaxMessageLines:(unsigned)lines;
-(void)setHighlighted:(BOOL)highlighted;
-(void)prepareForReuse;
-(void)dealloc;
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
@end

