/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinFadeOverlayOwner <NSObject>
-(void)setLinenGradientAlpha:(float)alpha;
-(void)setRasterizesFadeOverlay:(BOOL)overlay;
@end

