/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinWindowClient <NSObject>
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
@optional
-(void)bulletinWindowDidResignKey;
-(void)bulletinWindowDidBecomeKey;
-(BOOL)requiresKeyWindow;
@end

