/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;
@protocol SBBulletinClearButtonDelegate;

__attribute__((visibility("hidden")))
@interface SBBulletinClearButton : XXUnknownSuperclass {
	BOOL _showingClear;
	UIImageView* _backgroundView;
	UIImageView* _xImageView;
	UIImageView* _clearImageView;
	float _widthWhenShowingX;
	float _widthWhenShowingClear;
	id _clearShownAction;
	id _clearPressedAction;
	id<SBBulletinClearButtonDelegate> _delegate;
}
@property(copy, nonatomic) id clearPressedAction;
@property(copy, nonatomic) id clearShownAction;
@property(assign, nonatomic) id<SBBulletinClearButtonDelegate> delegate;
+(void)initialize;
+(void)_removeCachedClearImage;
-(id)_precompositedXImage;
-(id)_background;
-(id)_xImage;
-(id)_clearImage;
-(void)_setShowsClear:(BOOL)clear animated:(BOOL)animated;
-(void)_switchToUsingSubviews;
-(CGRect)_clearImageFrame;
-(CGRect)_xImageFrame;
-(CGRect)_xImageFrameInBounds:(CGRect)bounds;
-(void)_pressAction;
-(void)setHighlighted:(BOOL)highlighted;
-(void)resetAnimated:(BOOL)animated;
-(BOOL)showingClear;
-(void)dealloc;
-(id)init;
@end

