/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIView, SBBulletinBannerItem, UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinBannerView : XXUnknownSuperclass {
	SBBulletinBannerItem* _item;
	UIView* _iconView;
	UILabel* _titleLabel;
	UILabel* _messageLabel;
	float _imageWidth;
	UIImageView* _accessoryImageView;
	UIImageView* _backgroundImageView;
}
-(id)_backgroundImageWithAttachmentImage:(id)attachmentImage;
-(void)layoutSubviews;
-(void)_createSubviewsWithBackgroundImage:(id)backgroundImage;
-(void)dealloc;
-(id)bannerItem;
-(id)initWithItem:(id)item;
@end

