/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBBulletinLinenBackedCell : XXUnknownSuperclass {
	UIView* _linenView;
	BOOL _showsLinen;
}
@property(assign, nonatomic) BOOL showsLinen;
-(void)setFrame:(CGRect)frame;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)adjustLinenContents;
-(void)dealloc;
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
@end

