/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBCalendarController : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(void)_significantTimeChange;
-(void)_checkForTimeZoneIfNecessary;
-(void)_finishInitialization;
-(void)dealloc;
-(id)init;
@end

