/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay {
}
+(id)bottomBarForInstance:(id)instance;
+(id)topBarForInstance:(id)instance;
-(void)setAlert:(id)alert;
-(void)callBack:(id)back;
-(void)ignore:(id)ignore;
-(id)initWithFrame:(CGRect)frame;
@end

