/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CNFConferenceController;

__attribute__((visibility("hidden")))
@interface SBConferenceManager : XXUnknownSuperclass {
	CNFConferenceController* _conferenceController;
	unsigned _chatState;
}
@property(readonly, assign) unsigned chatState;
@property(readonly, assign) CNFConferenceController* conferenceController;
+(void)initialize;
+(id)sharedInstance;
-(void)_faceTimeAppActivationStateChanged:(id)changed;
-(void)_updateStatusBar;
-(void)updateStatusBar;
-(void)_faceTimeCapabilityChanged:(id)changed;
-(void)_faceTimeAvailabilityChanged:(id)changed;
-(id)currentCallStatusDisplayString;
-(id)currentCallRemoteUserId;
-(void)endFaceTime;
-(void)_faceTimeStateChanged:(id)changed;
-(void)_handleInvitation:(id)invitation;
-(void)dealloc;
-(BOOL)canStartFaceTime;
-(BOOL)inFaceTime;
-(BOOL)activeFaceTimeCallExists;
-(BOOL)faceTimeInvitationExists;
-(BOOL)faceTimeIsAvailable;
-(id)_faceTimeApp;
-(id)init;
@end

