/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBCornerViewFactory : XXUnknownSuperclass {
}
+(id)newCornerWindowForCorner:(int)corner windowLevel:(float)level cornersFrame:(CGRect)frame;
+(id)newCornerViewForCorner:(int)corner cornersFrame:(CGRect)frame;
@end

