/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBHUDView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBCompassRecalibrationView : SBHUDView {
}
-(id)init;
@end

