/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@protocol NSCopying;

@protocol SBCountedMapValue <NSObject>
@property(readonly, assign, nonatomic) id<NSCopying> countedMapKey;
@end

