/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAlertItem.h"

@class NSURL;

__attribute__((visibility("hidden")))
@interface SBDataPlanAccountAlertItem : SBDataPlanAlertItem {
	NSURL* _accountURL;
}
@property(copy, nonatomic) NSURL* accountURL;
+(id)nowButtonTitle;
+(id)laterButtonTitle;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithAccountURL:(id)accountURL;
@end

