/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBDataLookupResults : XXUnknownSuperclass {
	NSDictionary* _applicationDictionaries;
	NSMutableSet* _registeredBundleIDs;
	NSMutableSet* _unregisteredBundleIDs;
}
@property(readonly, assign) NSMutableSet* unregisteredBundleIDs;
@property(readonly, assign) NSMutableSet* registeredBundleIDs;
@property(readonly, assign) NSDictionary* applicationDictionaries;
-(void)updateWithResults:(id)results;
-(void)dealloc;
-(id)initWithApplicationDictionaries:(id)applicationDictionaries registeredBundleIDs:(id)ids unregisteredBundleIDs:(id)ids3;
@end

