/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableDictionary;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SBDaemonContext : XXUnknownSuperclass {
	NSObject<OS_dispatch_source>* _dispatchSource;
	NSMutableDictionary* _daemonRequests;
	int _pid;
}
-(id)description;
-(void)removeRequestForKey:(id)key;
-(void)addRequest:(id)request forKey:(id)key;
-(void)_handleCancelation;
-(id)_newDispatchSourceForPid:(int)pid queue:(id)queue;
-(int)pid;
-(void)dealloc;
-(id)initWithPid:(int)pid queue:(id)queue;
@end

