/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDataPlanAlertItem.h"


__attribute__((visibility("hidden")))
@interface SBDataPlanDisableAlertItem : SBDataPlanAlertItem {
}
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

