/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBDeviceLockPasscodeEntryAlert : SBAlert {
}
+(id)sharedInstance;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(int)statusBarStyle;
@end

