/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBDeviceLockPasscodeEntryAlertDisplay : SBSlidingAlertDisplay {
}
-(float)durationForOthersActivation;
-(float)delayForOthersActivation;
-(void)dismiss;
-(void)alertDisplayWillBecomeVisible;
-(void)deviceUnlockCanceled;
-(void)deviceUnlockSucceeded;
-(void)useEmergencyCallButton;
@end

