/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBIconModelPropertyListFileStore.h"

@class NSError;

@interface SBDefaultIconModelStore : SBIconModelPropertyListFileStore
{
}

+ (id)sharedInstance;

- (id)loadCurrentIconState:(id *)arg1;
- (id)loadDesiredIconState:(id *)arg1;
- (BOOL)saveDesiredIconState:(id)arg1 error:(NSError **)error;
- (BOOL)deleteDesiredIconState:(id *)arg1;
- (void)_deleteLegacyState;

@end

