/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDeviceLockDisableAssertion : XXUnknownSuperclass {
	NSString* _identifier;
	int _type;
}
-(void)dealloc;
-(int)type;
-(id)description;
-(id)initWithIdentifier:(id)identifier type:(int)type;
@end

