/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconModelPropertyListFileStore.h"


__attribute__((visibility("hidden")))
@interface SBDefaultIconModelStore : SBIconModelPropertyListFileStore {
}
+(id)sharedInstance;
-(void)_deleteLegacyState;
-(id)loadDesiredIconState:(id*)state;
-(BOOL)saveDesiredIconState:(id)state error:(id*)error;
-(BOOL)deleteDesiredIconState:(id*)state;
-(id)loadCurrentIconState:(id*)state;
-(id)init;
@end

