/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimeZone, PCPersistentTimer, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBDeviceLockController : XXUnknownSuperclass {
	int _deviceLockState;
	BOOL _isPermanentlyBlocked;
	BOOL _isBlockedForThermalCondition;
	double _deviceLockBlockTime;
	double _lastLockWallTime;
	NSTimeZone* _lastLockTimeZone;
	double _lastLockSecondsSinceBoot;
	PCPersistentTimer* _deviceLockTimer;
	int _gracePeriodWhenLocked;
	NSMutableSet* _preventLockAssertions;
	NSMutableSet* _gracePeriodSuspendAssertions;
	BOOL _okToSendNotifications;
}
+(id)sharedController;
-(void)removeDeviceLockDisableAssertion:(id)assertion;
-(void)addDeviceLockDisableAssertion:(id)assertion;
-(BOOL)_hasAnyActiveDeviceLockDisableAssertions;
-(BOOL)_hasActiveGracePeriodSuspendAssertions;
-(BOOL)_hasActivePreventLockAssertions;
-(BOOL)attemptDeviceUnlockWithPassword:(id)password appRequested:(BOOL)requested;
-(void)notePasscodeGracePeriodMayHaveChanged;
-(void)_clearBlockedState;
-(BOOL)isPermanentlyBlocked:(double*)blocked;
-(BOOL)isBlocked;
-(void)_setDeviceLockState:(int)state;
-(void)enableDeviceLock;
-(void)_clearDeviceLockedTimer;
-(BOOL)_shouldLockDeviceWithCurrentGracePeriod:(int)currentGracePeriod;
-(int)_getGracePeriod;
-(void)_beginGracePeriod;
-(void)_updateDeviceLockedState;
-(void)_setDeviceLockTimer;
-(BOOL)_shouldSetDeviceLockTimer;
-(void)_cancelGracePeriodIfNecessaryAndPossible;
-(BOOL)_shouldLockDeviceNow;
-(BOOL)_shouldBeginGracePeriodNow;
-(void)setBlockedForThermalCondition:(BOOL)thermalCondition;
-(void)_sendBlockStateChangeNotification;
-(BOOL)isBlockedForThermalCondition;
-(BOOL)isDeviceLockedOrBlocked;
-(BOOL)isDeviceLocked;
-(BOOL)isPasswordProtected;
-(id)lastLockDate;
-(void)profileConnectionDidReceivePasscodeChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)profileConnectionDidReceiveRestrictionChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)profileConnection userInfo:(id)info;
-(void)dealloc;
-(id)init;
@end

