/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBDefaultImageInfo : XXUnknownSuperclass {
	int _launchingInterfaceOrientation;
	float _launchingScale;
	int _originalOrientation;
	int _currentOrientation;
	BOOL _hasSnapshot;
	UIImage* _image;
}
@property(retain, nonatomic) UIImage* image;
@property(assign, nonatomic) BOOL hasSnapshot;
@property(assign, nonatomic) int currentOrientation;
@property(assign, nonatomic) int originalOrientation;
@property(assign, nonatomic) float launchingScale;
@property(assign, nonatomic) int launchingInterfaceOrientation;
-(id)description;
-(void)dealloc;
@end

