/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBDiskSpaceAlertItem : XXUnknownSuperclass {
	int _usageButtonIndex;
}
-(BOOL)shouldShowInEmergencyCall;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)_showUsagePrefs;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)performUnlockAction;
@end

