/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconLabelImageParameters.h"


__attribute__((visibility("hidden")))
@interface SBDisabledIconLabelImageParameters : SBIconLabelImageParameters {
}
-(id)textColor;
@end

