/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SSDownloadQueueObserver.h"

@class NSMutableSet, NSMutableArray, SSDownloadQueue, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBDownloadController : XXUnknownSuperclass <SSDownloadQueueObserver> {
	SSDownloadQueue* _downloadQueue;
	NSMutableSet* _pendingDownloadRemovals;
	NSMutableArray* _downloads;
	unsigned _downloadLoadCount;
	NSMutableDictionary* _bundleIDDownloadMap;
	BOOL _hasDownloadedStoreDownload;
}
+(id)sharedInstance;
-(void)downloadingIconStatusDidChange:(id)downloadingIconStatus;
-(id)bundleIdentifiersBeingDownloaded:(id)downloaded;
-(BOOL)bundledIdentifierIsBeingDownloaded:(id)downloaded;
-(BOOL)moveDownloadToFrontOfQueue:(id)queue;
-(void)cancelDownload:(id)download;
-(id)currentDownloads;
-(BOOL)checkQueue;
-(void)downloadQueueError:(id)error;
-(void)_showDownloadQueueError;
-(void)downloadQueueNetworkUsageChanged:(id)changed;
-(void)downloadQueue:(id)queue downloadStatusChangedAtIndex:(int)index;
-(void)_processDownloadQueueChangedWithPendingRemovals;
-(void)downloadQueue:(id)queue changedWithRemovals:(id)removals;
-(id)downloadWithBundleIdentifier:(id)bundleIdentifier;
-(void)_delayedDownloadQueueChange;
-(void)_downloadsEnded;
-(void)_downloadingIconWasRemoved:(id)removed;
-(void)_finishDownloadInStore:(id)store;
-(void)_finishDownloadInLocalState:(id)localState;
-(void)_finishDownload:(id)download;
-(BOOL)hasDownloadedStoreDownload;
-(void)dealloc;
-(id)init;
@end

