/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBDockIconListView : SBIconListView {
}
+(id)backgroundImageForOrientation:(int)orientation;
+(unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)columnAtPoint:(CGPoint)point;
-(CGPoint)originForIconAtX:(unsigned)x Y:(unsigned)y;
-(float)_additionalSideInsetToCenterIcons;
-(float)sideIconInset;
-(unsigned)rowAtPoint:(CGPoint)point;
-(float)topIconInset;
-(unsigned)iconsInRowForSpacingCalculation;
-(int)visibleIconsInDock;
-(void)setOrientation:(int)orientation duration:(double)duration;
-(void)setOrientation:(int)orientation;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)_updateForOrientation:(int)orientation duration:(double)duration;
-(id)initWithFrame:(CGRect)frame viewMap:(id)map;
-(id)initForOrientation:(int)orientation viewMap:(id)map;
@end

