/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIImageView;

__attribute__((visibility("hidden")))
@interface SBDownloadingProgressBar : XXUnknownSuperclass {
	UIView* _clipView;
	UIImageView* _fillView;
	float _progress;
}
+(float)defaultHeight;
-(void)updateFill;
-(float)progress;
-(void)setProgress:(float)progress;
-(id)fillImage;
-(id)trackImage;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

