/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconObserver.h"


@protocol SBDownloadingIconObserver <SBIconObserver>
@optional
-(void)downloadingIconStatusDidChange:(id)downloadingIconStatus;
@end

