/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBDownloadMetadataCache : XXUnknownSuperclass {
	NSMutableSet* _fetchedDownloads;
}
+(id)sharedInstance;
-(void)downloadRemoved:(id)removed;
-(BOOL)artworkIsPrerenderedForDownload:(id)download;
-(id)applicationIdentifierForDownload:(id)download;
-(id)bundleIdentifierForDownload:(id)download;
-(id)titleForDownload:(id)download;
-(id)softwareTypeForDownload:(id)download;
-(void)_ensureMetadataCachedForDownload:(id)download;
-(id)init;
@end

