/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBIconListView.h"
#import <UIKit/UIKit.h>

@class SBIconViewMap;

@interface SBDockIconListView : SBIconListView
{
}

+ (UIImage *)backgroundImageForOrientation:(UIInterfaceOrientation)arg1;
+ (NSUInteger)iconRowsForInterfaceOrientation:(int)arg1;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(int)arg1;
- (NSUInteger)columnAtPoint:(CGPoint)arg1;
- (CGPoint)originForIconAtX:(NSUInteger)arg1 Y:(NSUInteger)arg2;
- (CGFloat)_additionalSideInsetToCenterIcons;
- (CGFloat)sideIconInset;
- (NSUInteger)rowAtPoint:(CGPoint)arg1;
- (CGFloat)topIconInset;
- (NSUInteger)iconsInRowForSpacingCalculation;
- (NSInteger)visibleIconsInDock;
- (void)setOrientation:(UIInterfaceOrientation)arg1 duration:(NSTimeInterval)arg2;
- (void)setOrientation:(UIInterfaceOrientation)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_updateForOrientation:(UIInterfaceOrientation)arg1 duration:(NSTimeInterval)arg2;

- (id)initWithFrame:(CGRect)arg1 viewMap:(id)arg2;
- (id)initForOrientation:(UIInterfaceOrientation)arg1 viewMap:(SBIconViewMap *)arg2;

@end

