/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBEmergencyCallView : XXUnknownSuperclass {
	UIView* _topBar;
}
-(void)dealloc;
-(void)setTopBar:(id)bar;
-(id)topBar;
-(id)initWithFrame:(CGRect)frame topBarFrame:(CGRect)frame2 bottomBarFrame:(CGRect)frame3;
@end

