/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBFakeStatusBarView : XXUnknownSuperclass {
	BOOL _initialized;
}
@property(assign, nonatomic) BOOL initialized;
+(id)allocWithZone:(NSZone*)zone;
-(oneway void)release;
-(id)retain;
-(void)dealloc;
-(void)_clearChanges;
-(id)initWithFrame:(CGRect)frame;
@end

