/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNewsstandApplication.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBFakeNewsstandApplication : SBNewsstandApplication {
}
+(id)fakeApplication;
-(BOOL)isFakeApp;
-(id)init;
@end

