/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet;

__attribute__((visibility("hidden")))
@interface SBFolderRotationAnimationContext : XXUnknownSuperclass {
	NSSet* _icons;
	XXStruct_9ihRqB _notchInfo;
	double _duration;
}
@property(assign, nonatomic) double duration;
@property(assign, nonatomic) XXStruct_9ihRqB notchInfo;
@property(retain, nonatomic) NSSet* icons;
-(void)dealloc;
@end

