/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWallpaperView, SBFolderNotchView, SBFolderView, SBFolderNotchHighlightView, UIView, SBSlidingViewHighlight, UIImageView;

__attribute__((visibility("hidden")))
@interface SBFolderSlidingView : XXUnknownSuperclass {
	int _position;
	SBFolderView* _folderView;
	int _orientation;
	XXStruct_9ihRqB _notchInfo;
	CGRect _wallpaperRect;
	UIView* _rasterizationView;
	UIView* _wallpaperContainerView;
	SBWallpaperView* _wallpaperView;
	SBFolderNotchView* _linenNotchView;
	SBSlidingViewHighlight* _highlightView;
	SBFolderNotchHighlightView* _notchHighlightView;
	UIImageView* _dockView;
	UIImageView* _outgoingDockView;
}
-(void)handleGestureInWallpaperContainer:(id)wallpaperContainer;
-(void)setShouldRasterize:(BOOL)rasterize;
-(void)setShowsHighlight:(BOOL)highlight;
-(id)_newDockViewForOrientation:(int)orientation;
-(void)_placeNotchAndHighlights;
-(CGRect)_rectByAddingOverlapToRect:(CGRect)rect;
-(void)dealloc;
-(id)folderView;
-(void)setOrientation:(int)orientation wallpaperRect:(CGRect)rect notchInfo:(XXStruct_9ihRqB)info;
-(void)cleanUpAfterDockOrientationChange;
-(void)prepareToSetDockOrientation:(int)setDockOrientation;
-(id)initWithPosition:(int)position folderView:(id)view;
@end

