/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UITextInteractionAssistant;

__attribute__((visibility("hidden")))
@interface SBFolderTextField : XXUnknownSuperclass {
}
@property(readonly, assign, nonatomic) UITextInteractionAssistant* interactionAssistant;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(id)initWithFrame:(CGRect)frame;
@end

