/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


__attribute__((visibility("hidden")))
@interface SBFolderIconListView : SBIconListView {
}
+(unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
-(CGRect)nineIconRectForScrollPosition:(int)scrollPosition;
-(float)bottomIconInset;
-(float)topIconInset;
@end

