/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconIndexNodeObserver.h"
#import "SBIconObserver.h"
#import "SBIcon.h"
#import "SpringBoard-Structs.h"

@class NSMutableSet, SBFolder, NSHashTable;

__attribute__((visibility("hidden")))
@interface SBFolderIcon : SBIcon <SBIconObserver, SBIconIndexNodeObserver> {
	SBFolder* _folder;
	NSHashTable* _nodeObservers;
	NSMutableSet* _finishedDownloadIdentifiers;
	float _progress;
}
@property(readonly, assign) float progress;
+(Class)_iconGridImageClass;
+(unsigned)_maxIconsInGridImage;
-(id)folder;
-(BOOL)isFolderIcon;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(id)nodeDescriptionWithPrefix:(id)prefix;
-(void)removeNodeObserver:(id)observer;
-(void)addNodeObserver:(id)observer;
-(id)nodesAlongIndexPath:(id)path consumedIndexes:(unsigned)indexes;
-(id)indexPathsForContainedNodeIdentifier:(id)containedNodeIdentifier prefixPath:(id)path;
-(id)containedNodeIdentifiers;
-(BOOL)containsNodeIdentifier:(id)identifier;
-(id)nodeIdentifier;
-(void)downloadingIconStatusDidChange:(id)downloadingIconStatus;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)iconImageDidUpdate:(id)iconImage;
-(id)miniGridCellImageForIcon:(id)icon;
-(id)gridImageWithSkipping:(BOOL)skipping;
-(id)_miniIconGridWithSkipping:(BOOL)skipping;
-(unsigned)gridCellIndexForIconIndex:(unsigned)iconIndex withSkipping:(BOOL)skipping;
-(BOOL)gridImageShouldSkipIcons;
-(NSRange)_gridImageSkippedIconsRange;
-(void)_containedIconImageChanged:(id)changed;
-(void)noteContainedIcon:(id)icon replacedIcon:(id)icon2;
-(void)noteContainedIconsAdded:(id)added removed:(id)removed;
-(void)_adjustForIconsAdded:(id)iconsAdded removed:(id)removed;
-(void)updateProgress;
-(void)_updateProgressBar;
-(void)noteCompletedDownloadIdentifier:(id)identifier;
-(void)_updateBadgeValue;
-(void)updateLabel;
-(void)launch;
-(id)description;
-(void)localeChanged;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(id)displayName;
-(id)iconOverlayImageForLocation:(int)location;
-(id)getGenericIconImage:(int)image;
-(id)generateIconImage:(int)image;
-(void)dealloc;
-(id)initWithFolder:(id)folder;
@end

