/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBFolderNotchHighlightView : XXUnknownSuperclass {
	XXStruct_9ihRqB _notchInfo;
}
-(void)drawRect:(CGRect)rect;
-(id)initWithNotchInfo:(XXStruct_9ihRqB)notchInfo;
@end

