/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


__attribute__((visibility("hidden")))
@interface SBFolderIconListModel : SBIconListModel {
}
+(Class)viewClass;
@end

