/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"
#import "SBFolderIconObserver.h"

@class SBFolderIcon, SBDownloadingProgressBar, NSMutableSet, UIImageView;

__attribute__((visibility("hidden")))
@interface SBFolderIconView : SBIconView <SBFolderIconObserver> {
	UIImageView* _iconBackgroundView;
	UIImageView* _iconForegroundView;
	SBDownloadingProgressBar* _progressBar;
	NSMutableSet* _animatingIcons;
	unsigned _currentScrollRow;
	BOOL _skippingGridIcons;
	float _miniIconVisibleOffset;
}
@property(readonly, assign) SBFolderIcon* folderIcon;
-(void)folderIcon:(id)icon didUpdateGridImage:(id)image withSkipping:(BOOL)skipping forContainedIconImageUpdate:(id)containedIconImageUpdate;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)iconImageDidUpdate:(id)iconImage;
-(void)prepareForRecycling;
-(void)_updateProgressBar;
-(double)grabDurationForEvent:(id)event;
-(BOOL)delaysUnhighlightWhenTapped;
-(BOOL)allowsTapWhileEditing;
-(id)description;
-(id)folder;
-(void)positionCloseBoxOfType:(int)type;
-(id)iconBackgroundView;
-(id)progressBar;
-(void)setPartialGhostly:(float)ghostly requester:(int)requester;
-(void)setGhostly:(BOOL)ghostly requester:(int)requester;
-(void)placeGhostlyImageView;
-(id)_iconBoundsForAccessory:(CGRect*)accessory;
-(CGRect)frameForIconOverlay;
-(void)showDropGlow:(BOOL)glow;
-(CGAffineTransform)transformToMakeIconBorderExpandToSizeOfDropGlow;
-(void)positionIconImageView;
-(void)_positionMiniGrid;
-(id)iconImageSnapshot:(id)snapshot;
-(id)snapshotSettings;
-(id)_folderForegroundImage;
-(id)_folderBackgroundImage;
-(CGRect)rectForMiniIconAtIndex:(unsigned)index;
-(void)setIsOverlapping:(BOOL)overlapping;
-(void)setIconScrollPosition:(int)position animated:(BOOL)animated;
-(void)setIcon:(id)icon;
-(void)setFolderIcon:(id)icon;
-(void)dealloc;
@end

