/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBZoomView.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBFullscreenZoomView : SBZoomView {
	BOOL _hasImage;
	BOOL _hasFullSizedImage;
	int _corners;
	NSMutableArray* _cornerViews;
}
-(void)setRoundedCorners:(int)corners withCornersFrame:(CGRect)cornersFrame;
-(void)dealloc;
-(id)initWithView:(id)view;
-(id)initWithImage:(id)image;
-(id)initWithSnapshotFrame:(CGRect)snapshotFrame ioSurface:(void*)surface snapshotTransform:(CGAffineTransform)transform;
-(id)initWithSnapshotFrame:(CGRect)snapshotFrame image:(id)image originalImageOrientation:(int)orientation currentImageOrientation:(int)orientation4 interfaceOrientation:(int)orientation5 doubleHeightStatusBar:(BOOL)bar preventSplit:(BOOL)split chrome:(id)chrome chromeStatusBarHidden:(BOOL)hidden needsZoomFilter:(BOOL)filter asyncDecodeImage:(BOOL)image11;
-(id)_initWithFrame:(CGRect)frame;
@end

