/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBHostWrapperView, NSDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBHostRequesterInfo : XXUnknownSuperclass {
	SBHostWrapperView* _wrapperView;
	NSMutableSet* _hiddenContexts;
	NSDictionary* _realContextHostViewChangedProperties;
	NSDictionary* _realContextHostViewOriginalProperties;
}
@property(retain, nonatomic) NSDictionary* realContextHostViewOriginalProperties;
@property(retain, nonatomic) NSDictionary* realContextHostViewChangedProperties;
@property(readonly, assign, nonatomic) NSMutableSet* hiddenContexts;
@property(readonly, assign, nonatomic) SBHostWrapperView* wrapperView;
-(void)dealloc;
-(id)init;
@end

