/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBHomeCentricPopoverControllerDelegate <NSObject>
-(void)homeCentricPopoverDidDismissView:(id)homeCentricPopover;
-(void)homeCentricPopoverWillDismissView:(id)homeCentricPopover animated:(BOOL)animated;
-(void)homeCentricPopoverDidPresentView:(id)homeCentricPopover;
-(void)homeCentricPopoverWillPresentView:(id)homeCentricPopover animated:(BOOL)animated;
@end

