/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIPopoverControllerDelegatePrivate.h"
#import "SBUIActiveOrientationObserver.h"
#import "UIPopoverControllerDelegate.h"

@class UIPopoverController, UIWindow;
@protocol SBHomeCentricPopoverControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBHomeCentricPopoverController : XXUnknownSuperclass <UIPopoverControllerDelegate, UIPopoverControllerDelegatePrivate, SBUIActiveOrientationObserver> {
	UIWindow* _window;
	UIPopoverController* _popover;
	id<SBHomeCentricPopoverControllerDelegate> _delegate;
	BOOL _presented;
	int _presentedOrientation;
	unsigned _orientationChangeCount;
	BOOL _shouldSendDidPresent;
	BOOL _shouldSendDidDismiss;
}
@property(assign, nonatomic) BOOL ignoresKeyboardAvoidance;
@property(assign, nonatomic) id<SBHomeCentricPopoverControllerDelegate> delegate;
-(void)popoverController:(id)controller animationCompleted:(int)completed;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
-(void)activeInterfaceOrientationDidChangeToOrientation:(int)activeInterfaceOrientation willAnimateWithDuration:(double)duration fromOrientation:(int)orientation;
-(void)activeInterfaceOrientationWillChangeToOrientation:(int)activeInterfaceOrientation;
-(void)_commonDidDismiss;
-(void)_hidePopoverWindow;
-(void)dismissPopoverAnimated:(BOOL)animated;
-(void)setDesiredContentSize:(CGSize)size animated:(BOOL)animated;
-(BOOL)presentPopoverView:(id)view withDesiredContentSize:(CGSize)desiredContentSize animated:(BOOL)animated;
-(BOOL)isVisible;
-(void)dealloc;
-(id)init;
-(id)initWithUIPopoverControllerClass:(Class)uipopoverControllerClass;
@end

