/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIColor;

@protocol SBHostView <NSObject>
@property(retain, nonatomic) UIColor* backgroundColorWhileNotHosting;
@property(retain, nonatomic) UIColor* backgroundColorWhileHosting;
@end

