/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBCountedMapValue.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol NSCopying;

__attribute__((visibility("hidden")))
@interface SBIconAccessoryImage : XXUnknownSuperclass <SBCountedMapValue> {
	NSString* _text;
}
@property(readonly, assign, nonatomic) id<NSCopying> countedMapKey;
@property(readonly, assign, nonatomic) NSString* text;
+(void)checkinAccessoryImage:(id)image;
+(id)checkoutAccessoryImageForIcon:(id)icon location:(int)location;
+(Class)_imageClassForIcon:(id)icon location:(int)location;
+(id)_accessoryImageCountedMap;
+(id)textForCountedMapKey:(id)countedMapKey;
+(id)countedMapKeyForText:(id)text;
+(id)creationBlockForText:(id)text;
-(CGRect)accessoryFrameForIconBounds:(CGRect)iconBounds;
@end

