/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBIconAccessoryImage;

__attribute__((visibility("hidden")))
@interface SBIconAccessoryImageView : XXUnknownSuperclass {
	SBIconAccessoryImage* _baseImage;
	float _brightness;
	BOOL _brightnessHasBeenSet;
	BOOL _coalescingChanges;
	BOOL _needsUpdate;
}
@property(assign, nonatomic) float brightness;
@property(retain, nonatomic) SBIconAccessoryImage* image;
-(id)description;
-(void)_updateImage;
-(void)setImage:(id)image brightness:(float)brightness;
-(void)dealloc;
@end

