/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconAccessoryImage.h"


__attribute__((visibility("hidden")))
@interface SBIconBadgeImage : SBIconAccessoryImage {
}
+(id)creationBlockForText:(id)text;
+(float)_badgeLabelVerticalOffset;
-(CGRect)accessoryFrameForIconBounds:(CGRect)iconBounds;
-(id)countedMapKey;
-(void)dealloc;
-(id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation text:(id)text;
@end

