/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconIndexNodeObserver.h"
#import "SBIconObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconViewObserver.h"

@class SBIconModel, NSMapTable;
@protocol SBIconViewDelegate, SBIconViewMapDelegate;

__attribute__((visibility("hidden")))
@interface SBIconViewMap : XXUnknownSuperclass <SBIconObserver, SBIconIndexNodeObserver, SBIconViewObserver> {
	SBIconModel* _model;
	NSMapTable* _iconViewsForIcons;
	id<SBIconViewMapDelegate> _delegate;
	id<SBIconViewDelegate> _viewDelegate;
	NSMapTable* _recycledIconViewsByType;
	NSMapTable* _labels;
	NSMapTable* _badges;
}
@property(assign, nonatomic) id<SBIconViewDelegate> viewDelegate;
+(id)switcherMap;
+(id)homescreenMap;
-(void)iconViewDidChangeLocation:(id)iconView;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)_modelReloadedState;
-(void)_modelReloadedIcons;
-(void)_modelRemovedIcon:(id)icon;
-(void)purgeRecycledIconViewsForClass:(Class)aClass;
-(void)recycleAndPurgeAll;
-(void)recycleViewForIcon:(id)icon;
-(void)_recycleIconView:(id)view;
-(void)purgeIconFromMap:(id)map;
-(void)_addIconView:(id)view forIcon:(id)icon;
-(id)iconViewForIcon:(id)icon;
-(id)_iconViewForIcon:(id)icon;
-(id)mappedIconViewForIcon:(id)icon;
-(id)iconModel;
-(void)dealloc;
-(id)initWithIconModel:(id)iconModel delegate:(id)delegate;
@end

