/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconObserver <NSObject>
@optional
-(void)iconLaunchEnabledDidChange:(id)iconLaunchEnabled;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)iconImageDidUpdate:(id)iconImage;
@end

