/*
*     Generated by class-dump 3.3.4 (64 bit).
*
*     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
*/

#import <Foundation/NSObject.h>

#import "SBIconViewDelegate-Protocol.h"
#import "SBIconViewMapDelegate-Protocol.h"
#import "SBIconIndexNodeObserver-Protocol.h"
#import "SBIconObserver-Protocol.h"
#import "SBIconViewObserver-Protocol.h"

@class NSMapTable, SBIconModel, SBIconView;

@interface SBIconViewMap : NSObject <SBIconObserver, SBIconIndexNodeObserver, SBIconViewObserver>
{
    SBIconModel *_model;
    NSMapTable *_iconViewsForIcons;
    id<SBIconViewMapDelegate> _delegate;
    id<SBIconViewDelegate> _viewDelegate;
    NSMapTable *_recycledIconViewsByType;
    NSMapTable *_labels;
    NSMapTable *_badges;
}

@property(nonatomic, assign) id<SBIconViewDelegate> viewDelegate; // @synthesize viewDelegate=_viewDelegate;

+ (instancetype)switcherMap;
+ (instancetype)homescreenMap;

- (void)iconViewDidChangeLocation:(SBIconView *)iconView;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)iconAccessoriesDidUpdate:(id)arg1;
- (void)_modelReloadedState;
- (void)_modelReloadedIcons;
- (void)_modelRemovedIcon:(id)arg1;
- (void)purgeRecycledIconViewsForClass:(Class)arg1;
- (void)recycleAndPurgeAll;
- (void)recycleViewForIcon:(id)arg1;
- (void)_recycleIconView:(id)arg1;
- (void)purgeIconFromMap:(id)arg1;
- (void)_addIconView:(id)arg1 forIcon:(id)arg2;
- (SBIconView *)iconViewForIcon:(id)arg1;
- (SBIconView *)_iconViewForIcon:(id)arg1;
- (SBIconView *)mappedIconViewForIcon:(id)arg1;
- (SBIconModel *)iconModel;
- (instancetype)initWithIconModel:(SBIconModel *)arg1 delegate:(id<SBIconViewMapDelegate>)arg2;

@end

