/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class SBIconView;
@protocol SBIconViewDelegate <NSObject>

@optional
- (BOOL)iconViewDisplaysBadges:(SBIconView *)iconView;
- (BOOL)iconShouldPrepareGhostlyImage:(SBIconView *)iconView;
- (void)iconCloseBoxTapped:(SBIconView *)iconView;
- (int)closeBoxTypeForIcon:(SBIconView *)iconView;
- (void)icon:(SBIconView *)iconView openFolder:(id)arg2 animated:(BOOL)arg3;
- (void)icon:(SBIconView *)iconView closeFolderAnimated:(BOOL)arg2;
- (BOOL)icon:(SBIconView *)iconView canReceiveGrabbedIcon:(id)arg2;
- (void)iconTapped:(SBIconView *)iconView;
- (BOOL)iconShouldAllowTap:(SBIconView *)iconView;
- (void)icon:(id)arg1 touchEnded:(BOOL)arg2;
- (void)icon:(id)arg1 touchMovedWithEvent:(id)arg2;
- (void)iconTouchBegan:(SBIconView *)iconView;
- (void)iconHandleLongPress:(SBIconView *)iconView;
- (BOOL)iconPositionIsEditable:(SBIconView *)iconView;
- (BOOL)iconAllowJitter:(SBIconView *)iconView;

@end

