/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconModelStore.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface SBIconModelMemoryStore : XXUnknownSuperclass <SBIconModelStore> {
	NSDictionary* _currentState;
	NSDictionary* _desiredState;
}
@property(retain, nonatomic) NSDictionary* desiredState;
@property(retain, nonatomic) NSDictionary* currentState;
-(id)loadDesiredIconState:(id*)state;
-(id)loadCurrentIconState:(id*)state;
-(BOOL)deleteDesiredIconState:(id*)state;
-(BOOL)deleteCurrentIconState:(id*)state;
-(BOOL)saveDesiredIconState:(id)state error:(id*)error;
-(BOOL)saveCurrentIconState:(id)state error:(id*)error;
-(void)dealloc;
-(id)initWithCurrentState:(id)currentState desiredState:(id)state;
@end

