/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBIconScrollView : XXUnknownSuperclass {
}
-(void)setContentOffset:(CGPoint)offset;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(BOOL)cancelTouchTracking;
@end

