/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconViewMapDelegate <NSObject>
-(Class)viewMap:(id)map iconViewClassForIcon:(id)icon;
-(int)viewMap:(id)map locationForIcon:(id)icon;
-(unsigned)viewMap:(id)map maxRecycledIconViewsOfClass:(Class)aClass;
@optional
-(unsigned)viewMap:(id)map numberOfViewsToPrepareOfClass:(Class)aClass;
-(id)viewMapShouldPrepareViewsOfClasses:(id)viewMap;
@end

