/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>

@class NSMutableArray, NSMutableSet, SBIcon, SBIconView, SBIconListModel, SBIconViewMap;

@interface SBIconListView : UIView
{
    SBIconListModel *_model;
    SBIconViewMap *_viewMap;
    NSInteger _orientation;
    SBIcon *_bouncedIcon;
    NSMutableArray *_removedIcons;
    NSMutableArray *_iconContainerMatrix;
    NSUInteger _scattered:1;
    NSUInteger _needsLayout:1;
    NSUInteger _rotating:1;
    UIView *_fadeView;
    BOOL _iconsAreElsewhere;
    BOOL _recyclesIconViewsWhenNotShowing;
    NSMutableSet *_notShownIconViews;
    BOOL _showingCloseBoxes;
}

+ (NSUInteger)maxIcons;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(int)arg1;
+ (NSUInteger)maxVisibleIconRowsInterfaceOrientation:(int)arg1;
+ (NSUInteger)iconRowsForInterfaceOrientation:(int)arg1;

- (void)cleanupAfterRotation;
- (void)performRotationWithDuration:(NSTimeInterval)duration;
- (void)prepareToRotateToInterfaceOrientation:(UIInterfaceOrientation)arg1;
- (Class)iconRotationContainerClass;
- (id)rotationIconContainers; // instances of -[SBIconListView iconRotationContainerClass];
- (NSUInteger)_rotationReferenceRow;
- (NSUInteger)_postRotationFirstVisibleRow;
- (NSUInteger)_preRotationFirstVisibleRow;
- (NSUInteger)rowAtPoint:(CGPoint)arg1;
- (NSUInteger)columnAtPoint:(CGPoint)arg1;
- (CGPoint)originForIconAtX:(NSUInteger)arg1 Y:(NSUInteger)arg2;
- (CGFloat)verticalIconPadding;
- (CGFloat)horizontalIconPadding;
- (CGFloat)horizontalBumpForColumn:(NSUInteger)horizontalBump;
- (CGFloat)sideIconInset;
- (CGFloat)bottomIconInset;
- (CGFloat)topIconInset;
- (SBIcon *)bouncedIcon;
- (void)setBouncedIcon:(SBIcon *)icon;
- (BOOL)isDock;
- (void)makeIconViewsPerformBlock:(void(^)(SBIconView *))block;
- (void)makeIconsPerformBlock:(void(^)(SBIcon *))block;
- (void)makeIconViewsPerformSelector:(SEL)selector;
- (void)makeIconsPerformSelector:(SEL)selector;
- (void)hideCloseBoxes;
- (void)showCloseBoxes;
- (void)startJittering;
- (void)stopJittering;
- (void)showIconImagesFromColumn:(NSInteger)fromCol toColumn:(NSInteger)toCol totalColumns:(NSInteger)totalCols visibleIconsJitter:(BOOL)jitterVisible;
- (SBIcon *)iconAtPoint:(CGPoint)point index:(NSUInteger *)addrOfIndex proposedOrder:(NSInteger *)addrOfOrder grabbedIcon:(SBIcon *)icon;
- (SBIcon *)iconAtPoint:(CGPoint)arg1 index:(NSUInteger *)addrOfIndex;
- (CGFloat)layoutIconsIfNeeded:(CGFloat)animationDuration domino:(BOOL)domino;
- (CATransform3D)_transformForIconAtIndex:(NSUInteger)arg1 inOrientation:(int)arg2;
- (void)layoutIconsNow;
- (void)setIconsNeedLayout;
- (BOOL)recyclesIconViewsWhenNotShowing;
- (void)setRecyclesIconViewsWhenNotShowing:(BOOL)arg1;
- (BOOL)iconsAreElsewhere;
- (void)setIconsAreElsewhere:(BOOL)arg1;
- (void)setFrame:(CGRect)frame;
- (CGPoint)originForIcon:(SBIcon *)icon;
- (CGPoint)originForIconAtIndex:(NSInteger)index;
- (CGSize)defaultIconSize;
- (void)removeAllIconAnimations;
- (void)unscatterWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay;
- (void)unscatterAnimationDidStop;
- (void)scatterWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay;
- (void)setAlphaForAllIcons:(CGFloat)arg1;
- (BOOL)isScattered;
- (void)removeIcon:(SBIcon *)icon;
- (void)removeIconAtIndex:(NSUInteger)arg1;
- (id)removedIcons;
- (id)insertIcon:(SBIcon *)icon atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3;
- (id)insertIcon:(SBIcon *)icon atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (id)placeIcon:(id)arg1 atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_layoutIcon:(id)arg1 atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_noteNewIconInModel:(id)arg1;
- (void)_popIconView:(id)arg1;
- (void)showIconAnimationDidStop:(id)arg1 didFinish:(id)arg2 iconView:(id)arg3;
- (NSUInteger)firstFreeSlotOrLastSlotIndexForType:(int)arg1;
- (NSUInteger)firstFreeSlotOrLastSlotIndex;
- (NSUInteger)firstFreeSlotIndexForType:(int)arg1;
- (NSUInteger)firstFreeSlotIndex;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (NSArray *)visibleIcons;
- (NSArray *)icons;
- (BOOL)compactIcons:(BOOL)arg1;
- (NSUInteger)rowForIcon:(id)arg1;
- (void)getX:(NSUInteger *)addrOfX Y:(NSUInteger *)addrOfY forIndex:(NSUInteger)index forOrientation:(UIInterfaceOrientation)orientation;

// returns NSNotFound if icon at X/Y is non-existent
- (NSUInteger)indexForX:(NSUInteger)arg1 Y:(NSUInteger)arg2 forOrientation:(int)arg3;

- (void)setOrientation:(UIInterfaceOrientation)arg1;
- (NSUInteger)iconsInRowForSpacingCalculation;
- (NSUInteger)iconColumnsForCurrentOrientation;
- (NSUInteger)iconRowsForCurrentOrientation;
- (SBIconViewMap *)viewMap;
- (SBIconListModel *)model;
- (void)setModel:(SBIconListModel *)arg1;
- (instancetype)initWithFrame:(CGRect)frame;
- (instancetype)initWithFrame:(CGRect)frame viewMap:(SBIconViewMap *)viewMap; // If viewMap is nil, an empty SBIconViewMap object is set as the view map (accessible via -[SBIconListView viewMap])
- (Class)modelClass;

@end

