/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconModelDelegate <NSObject>
@optional
-(void)didDeleteIconState:(id)state;
-(void)didSaveIconState:(id)state;
-(BOOL)canSaveIconState:(id)state;
@end

