/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBIconImageContainerView : XXUnknownSuperclass {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

