/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconAccessoryImage.h"


__attribute__((visibility("hidden")))
@interface SBIconSashImage : SBIconAccessoryImage {
}
+(id)creationBlockForText:(id)text;
+(id)sashWithText:(id)text;
+(float)_labelMinFontSize;
+(float)_labelMaxFontSize;
+(BOOL)_showsLabel;
+(CGPoint)_sashCenterPoint;
+(float)_sashWidth;
+(UIEdgeInsets)_sashImageInsets;
+(id)_baseImage;
-(CGRect)accessoryFrameForIconBounds:(CGRect)iconBounds;
-(id)countedMapKey;
-(void)dealloc;
-(id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation text:(id)text;
@end

