/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIcon.h"
#import "SpringBoard-Structs.h"
#import "NSCopying.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBLeafIcon : SBIcon <NSCopying> {
	NSString* _leafIdentifier;
}
-(id)nodeIdentifier;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)description;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(id)leafIdentifier;
-(void)dealloc;
-(id)initWithLeafIdentifier:(id)leafIdentifier;
@end

