/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBLinenView : XXUnknownSuperclass {
	int _type;
	NSMutableArray* _strips;
}
@property(assign, nonatomic) int type;
+(float)_vOffsetOfTopForType:(int)type;
+(CGRect)_scaledRectForIndex:(unsigned)index ofImage:(id)image;
+(id)_imageKeyForIndex:(unsigned)index;
+(id)_cachedImageForIndex:(unsigned)index;
+(unsigned)_maximumNumberOfStrips;
+(void)_generateStripsIfNecessary;
+(id)squareImageForBounds:(CGRect)bounds;
+(float)naturalWidth;
+(void)load;
-(float)_vOffsetOfTop;
-(void)layoutSubviews;
-(void)_layoutForBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

