/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenAudioRoutesAlertItem : XXUnknownSuperclass {
}
-(void)audioRoutingPicker:(id)picker didSelectRouteAtIndex:(int)index;
-(void)performUnlockAction;
-(BOOL)allowAutoUnlock;
-(BOOL)togglesMediaControls;
-(BOOL)shouldShowInLockScreen;
-(void)willRelockForButtonPress:(BOOL)buttonPress;
-(BOOL)allowMenuButtonDismissal;
-(id)alertSheet;
-(Class)alertSheetClass;
@end

