/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBNewsstandTilingImageView : XXUnknownSuperclass {
	UIImage* _tileImage;
}
@property(retain, nonatomic) UIImage* _tileImage;
@property(retain, nonatomic) UIImage* image;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

