/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"

@class SBDownloadingProgressBar;

__attribute__((visibility("hidden")))
@interface SBNewsstandItemIconViewBase : SBIconView {
	SBDownloadingProgressBar* _progressBar;
}
+(Class)_labelImageParametersClassForIcon:(id)icon location:(int)location;
-(void)downloadingIconStatusDidChange:(id)downloadingIconStatus;
-(void)_adjustProgressBarFrame;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)_updateProgressBar;
-(void)_removeProgressBar;
-(void)_updateLabelVisibility;
-(UIEdgeInsets)_viewInsetsForAccessoryType:(int)accessoryType;
-(id)_iconBoundsForAccessory:(CGRect*)accessory;
-(void)iconImageDidUpdate:(id)iconImage;
-(id)initWithFrame:(CGRect)frame;
@end

