/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFolder.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandFolder : SBFolder {
}
+(int)maxListCount;
-(id)nodeIdentifier;
-(void)_setDisplayNameFromRepresentation:(id)representation;
-(BOOL)canAddIcon;
-(id)folderType;
-(BOOL)isNewsstandFolder;
-(Class)folderViewClass;
-(Class)listViewClass;
-(Class)listModelClass;
-(void)setIsOpen:(BOOL)open;
-(id)icon;
-(id)init;
@end

