/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUserInstalledApplicationIcon.h"

@class SBNewsstandApplication;

__attribute__((visibility("hidden")))
@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon {
	SBNewsstandApplication* _fakeApp;
}
@property(retain, nonatomic) SBNewsstandApplication* fakeApp;
+(id)iconOverlayImageForIcon:(id)icon inLocation:(int)location;
-(id)_newlyInstalledSashLabel;
-(BOOL)_shouldShowSashForNewlyInstalledApp;
-(id)badgeTextForLocation:(int)location;
-(id)badgeNumberOrString;
-(int)accessoryTypeForLocation:(int)location;
-(id)gridCellImage;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)iconOverlayImageForLocation:(int)location;
-(id)getGenericIconImage:(int)image;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)isNewsstandApplicationIcon;
-(int)iconFormatForLocation:(int)location;
-(void)launch;
-(BOOL)launchEnabled;
-(id)application;
-(BOOL)shouldWarmUp;
-(void)dealloc;
-(id)initWithApplication:(id)application;
@end

