/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, NSTimer;

__attribute__((visibility("hidden")))
@interface SBNewsstandCardView : XXUnknownSuperclass {
	BOOL _skewed;
	BOOL _highlighted;
	BOOL _touchOnCard;
	UIImageView* _cardView;
	UIImageView* _textView;
	UIImageView* _overlayView;
	NSTimer* _delayedUnhighlightTimer;
}
+(void)setupCache;
+(void)_fetchAndCacheImagesIfNecessary:(id*)necessary outCardTextImage:(id*)image;
+(void)_fetchAndCacheImagesIfNecessary;
+(void)_removeCachedLocalizedImages;
+(void)load;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)setHighlighted:(BOOL)highlighted delayUnhighlight:(BOOL)unhighlight;
-(void)_delayedUnhighlight;
-(id)overlayImage;
-(float)shadowPadding;
-(void)setSkewed:(BOOL)skewed;
-(CATransform3D)skewTransform;
-(void)dealloc;
-(id)init;
@end

