/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconSashImage.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandSwitcherSashImage : SBIconSashImage {
}
+(float)_labelMinFontSize;
+(float)_labelMaxFontSize;
+(CGPoint)_sashCenterPoint;
+(float)_sashWidth;
+(UIEdgeInsets)_sashImageInsets;
+(id)_baseImage;
@end

