/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIconView.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandIconView : SBFolderIconView {
}
-(void)placeIconOverlayView;
-(void)positionIconImageView;
-(id)_folderForegroundImage;
-(id)_folderBackgroundImage;
@end

