/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBNewsstand : XXUnknownSuperclass {
}
+(BOOL)addFakeApps;
+(BOOL)debugRotation;
+(id)bundleIDToReplicate;
+(BOOL)addManyIcons;
+(BOOL)alwaysShowIconLabels;
+(BOOL)disableIconSkew;
+(BOOL)_newsstandStoreIsSupported;
+(BOOL)_newsstandStoreIsRestricted;
+(BOOL)newsstandStoreIsAvailable;
+(BOOL)newsstandEnabled;
+(void)_iconVisibilityDidChange:(id)_iconVisibility;
+(void)_availableStoreItemKindsDidChange:(id)_availableStoreItemKinds;
+(void)reloadDefaults;
+(void)noteCapabilitiesDidChange;
+(void)_checkStoreSupport;
+(void)_updateStoreAvailability;
+(void)_loadDefaults;
+(void)openNewsstandAppStore;
+(void)initialize;
@end

