/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconGridImage.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandIconGridImage : SBIconGridImage {
}
+(CGRect)rectAtIndex:(unsigned)index forImage:(id)image maxCount:(unsigned)count;
+(CGSize)cellSpacing;
+(CGSize)cellSize;
@end

