/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBNetworkReselectionAlert : SBAlert {
}
+(void)_serviceAvailabilityChanged:(id)changed;
+(void)test;
+(void)registerForAlerts;
@end

