/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderScrollOffset.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandFolderScrollOffset : SBFolderScrollOffset {
	unsigned _firstVisibleRow;
}
@property(assign) unsigned firstVisibleRow;
@end

