/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfTableView : XXUnknownSuperclass {
	UIView* _backView;
}
@property(assign, nonatomic) UIView* shelfFrameView;
-(void)reloadData;
-(void)willRemoveSubview:(id)subview;
-(void)didAddSubview:(id)subview;
@end

