/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNewsstandTilingImageView.h"
#import "SpringBoard-Structs.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfHeaderView : SBNewsstandTilingImageView {
	float _borderWidth;
	UIImageView* _appleLogo;
	UIImageView* _middleShadow;
	UIImageView* _shelvesTopShading;
	int _orientation;
}
+(id)backgroundImage;
+(void)load;
-(void)layoutSubviews;
-(void)configureForOrientation:(int)orientation;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

