/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBNewsstandTilingImageView, SBNewsstandShelfHeaderView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfFrameView : XXUnknownSuperclass {
	CGSize _borderSize;
	SBNewsstandShelfHeaderView* _headerView;
	SBNewsstandTilingImageView* _leftBorder;
	SBNewsstandTilingImageView* _rightBorder;
	int _orientation;
}
-(void)layoutSubviews;
-(void)configureForOrientation:(int)orientation;
-(void)setFrame:(CGRect)frame;
-(void)showHeaderView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

