/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UISlider, UIButton, UIView, SBIconView, SBNowPlayingBarMediaControlsView, UIImageView;

__attribute__((visibility("hidden")))
@interface SBNowPlayingBarView : XXUnknownSuperclass {
	int _toggleType;
	UIView* _toggleButtonContainer;
	UIButton* _toggleButton;
	UISlider* _brightnessSlider;
	UISlider* _volumeSlider;
	UIImageView* _brightnessImage;
	UIImageView* _volumeImage;
	SBNowPlayingBarMediaControlsView* _mediaView;
	SBIconView* _nowPlayingIconView;
}
@property(assign, nonatomic) BOOL marqueeRunning;
@property(readonly, assign, nonatomic) UIButton* airPlayButton;
@property(retain, nonatomic) SBIconView* nowPlayingIconView;
@property(readonly, assign, nonatomic) SBNowPlayingBarMediaControlsView* mediaView;
@property(readonly, assign, nonatomic) UISlider* volumeSlider;
@property(readonly, assign, nonatomic) UISlider* brightnessSlider;
@property(readonly, assign, nonatomic) UIButton* toggleButton;
@property(assign, nonatomic) int toggleType;
-(void)showVolume:(BOOL)volume;
-(void)showAudioRoutesPickerButton:(BOOL)button;
-(void)_updateToggleButton;
-(void)_layoutForiPad;
-(void)_layoutForiPhone;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

