/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBPanGestureRecognizer.h"


__attribute__((visibility("hidden")))
@interface SBOffscreenSwipeGestureRecognizer : SBPanGestureRecognizer {
	int m_offscreenEdge;
	float m_edgeMargin;
	float m_falseEdge;
	int m_touchesChecked;
	CGPoint m_firstTouch;
	float m_edgeCenter;
	float m_allowableDistanceFromEdgeCenter;
	BOOL m_requiresSecondTouchInRange;
}
@property(assign, nonatomic) float edgeCenter;
@property(assign, nonatomic) BOOL requiresSecondTouchInRange;
@property(assign, nonatomic) float allowableDistanceFromEdgeCenter;
@property(assign, nonatomic) float falseEdge;
@property(assign, nonatomic) float edgeMargin;
-(void)updateForBeganOrMovedTouches:(SBGestureContextRef)beganOrMovedTouches;
-(void)_updateAnimationDistanceAndEdgeCenter;
-(BOOL)secondTouchInRange:(CGPoint)range;
-(BOOL)firstTouchInRange:(CGPoint)range;
-(void)reset;
-(id)initForOffscreenEdge:(int)offscreenEdge;
@end

