/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"
#import "SpringBoard-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBPasscodeAlertItem : XXUnknownSuperclass <UITextFieldDelegate> {
	int _mode;
	int _unlockScreenType;
	NSString* _errorString;
	BOOL _hasEmergencyCall;
}
-(void)didEndCall;
-(void)_setErrorString:(id)string;
-(void)dismiss:(int)dismiss;
-(BOOL)shouldShowInLockScreen;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)returnKeyPressed:(id)pressed;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)dealloc;
-(id)initWithPasscodeMode:(int)passcodeMode unlockScreenType:(int)type;
@end

