/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDate, SBPasscodeAlertItem, SBPasscodeComplianceAlertItem;

__attribute__((visibility("hidden")))
@interface SBPasscodeController : XXUnknownSuperclass {
	SBPasscodeAlertItem* _passcodeAlertItem;
	int _mode;
	NSString* _previousPasscode;
	NSString* _newPasscode;
	int _unlockScreenType;
	SBPasscodeComplianceAlertItem* _complianceAlertItem;
	NSDate* _forcedComplianceDate;
	id _telephonyNotificationObserver;
}
+(id)sharedInstance;
-(void)checkPasscodeCompliance;
-(void)_stopListeningToTelephonyNotifications;
-(void)_startListeningToTelephonyNotifications;
-(void)_didEndCall;
-(void)_abort;
-(void)_userWantsToComplyNow:(BOOL)complyNow;
-(void)_passwordEntered:(id)entered;
-(void)forceUserToChangePasscode;
-(void)dealloc;
@end

