/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWaveView.h"


__attribute__((visibility("hidden")))
@interface SBPathWaveView : SBWaveView {
}
+(Class)layerClass;
-(void)layoutSubviews;
-(void)setColor:(id)color;
-(void)_updateCurrentPath;
-(CGPathRef)_copyCurrentPath;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(id)initWithFrame:(CGRect)frame;
-(id)_shapeLayer;
@end

