/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBPowerDownViewDelegate
-(void)powerDownViewAnimateOutCompleted:(id)completed;
-(void)powerDownViewRequestPowerDown:(id)down;
-(void)powerDownViewRequestCancel:(id)cancel;
@end

