/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBPowerDownViewDelegate.h"
#import "SBAlert.h"

@class SBPowerDownView;

__attribute__((visibility("hidden")))
@interface SBPowerDownController : SBAlert <SBPowerDownViewDelegate> {
	int _count;
	id _delegate;
	SBPowerDownView* _powerDownView;
	BOOL _isFront;
	id _orderOutCompletion;
}
@property(copy, nonatomic) id orderOutCompletion;
+(id)sharedInstance;
-(void)powerDownViewAnimateOutCompleted:(id)completed;
-(void)powerDownViewRequestPowerDown:(id)down;
-(void)powerDownViewRequestCancel:(id)cancel;
-(void)cancel;
-(void)powerDown;
-(void)setDelegate:(id)delegate;
-(void)alertDisplayWillBecomeVisible;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)lockedOnTop;
-(void)deactivate;
-(void)_restoreIconListIfNecessary;
-(void)activate;
-(id)powerDownViewWithSize:(CGSize)size;
-(void)orderOutWithCompletion:(id)completion;
-(void)orderFront;
-(BOOL)isOrderedFront;
-(double)autoLockTime;
-(void)dealloc;
-(id)init;
@end

