/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBRelaunchAppWorkspaceTransaction.h"


__attribute__((visibility("hidden")))
@interface SBRelaunchBuddyWorkspaceTransaction : SBRelaunchAppWorkspaceTransaction {
}
-(void)_commit;
-(id)_setupAnimationForApp:(id)app;
@end

