/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDismissOnlyAlertItem.h"


__attribute__((visibility("hidden")))
@interface SBReorderInfoAlert : SBDismissOnlyAlertItem {
}
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)didDeactivateForReason:(int)reason;
@end

