/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication, NSString, SBProxyRemoteView;

__attribute__((visibility("hidden")))
@interface SBRemoteViewInfo : XXUnknownSuperclass {
	NSString* _remoteViewIdentifier;
	SBProxyRemoteView* _proxyRemoteView;
	unsigned _contextID;
	SBApplication* _application;
	CGSize _viewSize;
}
@property(assign, nonatomic) CGSize viewSize;
@property(retain, nonatomic) SBApplication* application;
@property(assign, nonatomic) unsigned contextID;
@property(retain, nonatomic) SBProxyRemoteView* proxyRemoteView;
@property(retain, nonatomic) NSString* remoteViewIdentifier;
-(void)dealloc;
@end

