/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBRenderImage : XXUnknownSuperclass {
	CARenderImageRef _image;
}
-(void*)CA_copyRenderValue;
-(void)dealloc;
-(id)initWithRenderImage:(CARenderImageRef)renderImage;
@end

