/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFluidSlideGestureRecognizer.h"


__attribute__((visibility("hidden")))
@interface SBScaleGestureRecognizer : SBFluidSlideGestureRecognizer {
}
-(float)computeIncrementalGestureMotion:(SBGestureContextRef)motion;
@end

