/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, UILabel, UISearchBar, UIView, SBNoResultsView, UITableView;

__attribute__((visibility("hidden")))
@interface SBSearchView : XXUnknownSuperclass {
	UISearchBar* _searchBar;
	UITableView* _tableView;
	UILabel* _noResultsLabel;
	SBNoResultsView* _noResultsView;
	UIView* _rootView;
	UIView* _contentView;
	BOOL _isKeyboardAnimatingRotation;
	BOOL _hidesEmptyTableFooter;
	BOOL _translatedKbForScatter;
	BOOL _deferredFirstResponder;
	BOOL _observingForKeyboardOnScreen;
	BOOL _observingForKeyboardOffScreen;
	BOOL _removeView;
	NSMutableArray* _keyboardCompletionBlocks;
}
@property(retain, nonatomic) UIView* rootView;
@property(retain, nonatomic) UIView* contentView;
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(readonly, assign, nonatomic) UISearchBar* searchBar;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)unscatterAnimationDidStop;
-(void)unscatter:(BOOL)unscatter delay:(double)delay;
-(void)scatter:(BOOL)scatter delay:(double)delay;
-(void)cleanupKeyboardForScatterIfNecessary;
-(void)_resetKeyboardTransformForScatter;
-(void)_resetContentViewTransform;
-(void)_setDistantContentViewTransform;
-(void)setShowingNoResultsText:(BOOL)text;
-(void)keyboardDidShow:(id)keyboard;
-(void)keyboardDidHide:(id)keyboard;
-(void)finishBecomingFirstResponderIfNecessary;
-(void)setShowsKeyboard:(BOOL)keyboard animated:(BOOL)animated shouldDeferResponderStatus:(BOOL)status completionBlock:(id)block;
-(void)setShowsKeyboard:(BOOL)keyboard animated:(BOOL)animated shouldDeferResponderStatus:(BOOL)status;
-(void)setShowsKeyboardAnimated:(BOOL)animated completionBlock:(id)block;
-(void)setShowsKeyboard:(BOOL)keyboard animated:(BOOL)animated;
-(BOOL)isKeyboardVisible;
-(void)__searchFieldDidResignFirstResponder;
-(void)_stopObservingForKeyboardOnScreen;
-(void)_startObservingForKeyboardOnScreen;
-(void)_stopObservingForKeyboardOffScreen;
-(void)_startObservingForKeyboardOffScreen;
-(void)__becomeFirstResponder;
-(BOOL)__isFirstResponder;
-(BOOL)isKeyboardMinimized;
-(id)_keyboard;
-(Class)searchBarClass;
-(Class)tableViewClass;
-(void)_layoutNoResultsView;
-(void)layoutFooterView;
-(float)_footerHeight;
-(void)setHidesEmptyTableFooter:(BOOL)footer;
-(void)layoutCornerView;
-(void)_resetLastCellInTableView;
-(void)setShowsNoResultsView:(BOOL)view;
-(void)scrollViewIsScrollingHorizontally;
-(void)setFrame:(CGRect)frame;
-(void)didMoveToWindow;
-(void)dealloc;
-(void)hideAllSubviewsOfTableView;
-(id)initWithFrame:(CGRect)frame withContent:(id)content onWallpaper:(id)wallpaper;
-(void)removeTableView;
-(void)addTableView;
-(id)initWithFrame:(CGRect)frame;
@end

