/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SPDaemonQueryDelegate.h"

@class NSObject, NSDate, NSTimer, NSMutableDictionary;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface SBSearchModel : XXUnknownSuperclass <SPDaemonQueryDelegate> {
	NSTimer* _clearSearchTimer;
	NSDate* _clearSearchDate;
	NSMutableDictionary* _cachedImages;
	NSObject<OS_dispatch_semaphore>* _cacheLock;
}
+(id)sharedInstance;
-(id)_customImageForPath:(id)path;
-(id)imageForDisplayIdentifier:(id)displayIdentifier spotlightKey:(id)key;
-(id)imageViewForDomain:(unsigned)domain andDisplayID:(id)anId;
-(id)_imageForDomain:(unsigned)domain andDisplayID:(id)anId;
-(void)handleOptionsForNewSections:(id)newSections;
-(id)launchingURLForResult:(id)result withDisplayIdentifier:(id)displayIdentifier andSection:(id)section;
-(void)_updateClearSearchTimerFireDate;
-(void)startClearSearchTimer;
-(void)_clearSearchTimerFired;
-(void)resetClearSearchTimer;
-(void)dealloc;
-(id)init;
@end

