/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIControl, UIWindow, SBSlidingViewHighlight;
@protocol SBShowcaseViewControllerProtocol, SBShowcaseControllerOwner;

__attribute__((visibility("hidden")))
@interface SBShowcaseController : XXUnknownSuperclass {
	UIWindow* _hostWindow;
	UIView* _hostView;
	UIWindow* _showcaseWindow;
	UIView* _rootView;
	UIView* _contentView;
	UIControl* _blockingView;
	UIView* _clippingView;
	UIView* _showcaseView;
	UIView* _topShadowView;
	UIView* _bottomShadowView;
	UIView* _hidingView;
	SBSlidingViewHighlight* _separator;
	float _revealAmount;
	int _orientation;
	BOOL _isAnimating;
	int _pendingRevealMode;
	id<SBShowcaseControllerOwner> _owner;
	id<SBShowcaseViewControllerProtocol> _showcaseViewController;
}
@property(assign, nonatomic, getter=isAnimating) BOOL animating;
@property(assign, nonatomic) int revealMode;
@property(assign, nonatomic) float revealAmount;
@property(assign, nonatomic) int orientation;
@property(readonly, assign, nonatomic) UIWindow* window;
@property(readonly, assign, nonatomic) UIControl* blockingView;
@property(retain, nonatomic) UIView* hidingView;
@property(retain, nonatomic) UIView* hostView;
@property(assign, nonatomic) id<SBShowcaseControllerOwner> owner;
@property(retain, nonatomic) id<SBShowcaseViewControllerProtocol> showcase;
+(float)fullRevealAmount;
-(BOOL)transferOwnershipToOwner:(id)owner;
-(void)noteRevealModeWillChange:(int)noteRevealMode;
-(void)dismissWithFadeOfDuration:(double)duration;
-(void)dismissWithAnimation:(BOOL)animation;
-(void)updateRevealMode:(int)mode withBlock:(id)block;
-(float)_showcaseRevealedAmount;
-(CGRect)_hostViewFrame;
-(CGRect)_adjustedContentFrameForFrame:(CGRect)frame;
-(CGRect)_portraitAdjustedFrameForFrame:(CGRect)frame;
-(CGRect)_contentFrame;
-(CGAffineTransform)_rootTransform;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didDisappear;
-(void)willDisappear;
-(void)didAppear;
-(void)willAppear;
-(float)_separatorAlphaForRevealAmount:(float)revealAmount;
-(CGRect)_visibleShowcaseBounds;
-(void)_updateShowcase;
-(void)_updateShowcaseWindowLevel;
-(float)_showcaseWindowLevel;
-(void)setAlpha:(float)alpha;
-(void)setHidden:(BOOL)hidden;
-(float)revealAmountForMode:(int)mode;
-(float)bottomBarHeight;
-(CGRect)showcaseViewFrame;
-(void)dealloc;
-(id)init;
@end

