/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBShowcaseControllerOwner <NSObject>
-(void)showcase:(id)showcase didTransferOwnershipToOwner:(id)owner;
-(void)assumeShowcaseOwnership:(id)ownership;
-(void)showcaseWantsToBeDismissed:(id)beDismissed animated:(BOOL)animated;
-(void)showcase:(id)showcase updateRevealMode:(int)mode withBlock:(id)block;
-(BOOL)presentShowcaseViewController:(id)controller revealMode:(int)mode completion:(id)completion;
@optional
-(float)showcaseWindowLevel:(id)level;
@end

