/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBSlidingAlertDisplayDelegate <NSObject>
@optional
-(void)slidingAlertViewDeactivationAnimationCompleted:(id)completed;
-(void)slidingAlertViewDeactivationAnimationStart:(id)start;
-(void)didToggleDeviceLock;
-(void)willAnimateToggleDeviceLockWithStyle:(int)style toVisibility:(BOOL)visibility withDuration:(double)duration;
-(void)willToggleDeviceLockWithStyle:(int)style toVisibility:(BOOL)visibility;
@end

