/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBSlidingViewHighlight : XXUnknownSuperclass {
	UIImageView* _leftHighlight;
	UIImageView* _rightHighlight;
	CGRect _notchRect;
}
+(id)highlightImage;
+(float)defaultHeight;
-(void)dealloc;
-(void)setNotchRect:(CGRect)rect;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame notchRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
@end

