/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplication.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBSMSApplication : SBApplication {
}
-(id)activationValue:(unsigned)value;
@end

