/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"


__attribute__((visibility("hidden")))
@interface SBSoftwareUpdateAvailableAlertItem : SBBaseSoftwareUpdateAlertItem {
}
-(BOOL)dismissOnLock;
-(BOOL)reappearsAfterUnlock;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
@end

