/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSDateFormatter, NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface SBStatusBarDataManager : XXUnknownSuperclass {
	XXStruct_dUflDB _data;
	int _actions;
	BOOL _itemIsEnabled[24];
	BOOL _itemIsCloaked[24];
	BOOL _telephonyAndBluetoothCloaked;
	BOOL _allButBatteryCloaked;
	BOOL _timeCloaked;
	int _updateBlockDepth;
	BOOL _dataChangedSinceLastPost;
	NSDateFormatter* _timeItemDateFormatter;
	NSTimer* _timeItemTimer;
	NSString* _timeItemTimeString;
	BOOL _simulateInCallStatusBar;
	NSString* _serviceString;
	NSString* _serviceCrossfadeString;
	NSString* _serviceImages[2];
	NSString* _operatorDirectory;
	BOOL _showsActivityIndicatorOnHomeScreen;
	BOOL _showsActivityIndicatorForNewsstand;
	int _syncActivityIndicatorCount;
	int _activityIndicatorEverywhereCount;
	int _thermalColor;
	BOOL _thermalSunlightMode;
	NSString* _recordingAppString;
	BOOL _showingNotChargingItem;
	NSString* _batteryDetailString;
}
+(id)sharedDataManager;
-(BOOL)_shouldShowEmergencyOnlyStatus;
-(BOOL)_getServiceImageNames:(id [2])names directory:(id*)directory forOperator:(id)anOperator statusBarCarrierName:(id*)name;
-(id)_displayStringForRegistrationStatus:(int)registrationStatus;
-(id)_displayStringForSIMStatus:(id)simstatus;
-(BOOL)_simStatusMeansLocked:(id)locked;
-(void)toggleSimulatesInCallStatusBar;
-(void)_updateTelephonyState;
-(void)_updateBatteryDetail;
-(BOOL)_shouldShowNotChargingItem;
-(void)_restartTimeItemTimer;
-(void)_stopTimeItemTimer;
-(void)_configureTimeItemDateFormatter;
-(void)_assistantChange;
-(void)_quietModeChange;
-(void)_rotationLockChange;
-(void)_locationStatusChange;
-(void)_bluetoothBatteryChange;
-(void)_bluetoothChange;
-(void)airplaneModeChanged;
-(void)_dataConnectionTypeChange;
-(void)_dataNetworkChange;
-(void)_vpnChange;
-(void)_callForwardingChange;
-(void)_ttyChange;
-(void)_signalStrengthChange;
-(void)_operatorChange;
-(void)_notChargingStatusChange;
-(void)_batteryStatusChange;
-(void)_didWakeFromSleep;
-(void)_localeChanged;
-(void)_significantTimeChanged;
-(void)_registerForNotifications;
-(void)_updateThermalColorItem;
-(void)_updateAssistantItem;
-(void)_updateQuietModeItem;
-(void)_updateRotationLockItem;
-(void)_updateLocationItem;
-(void)_updatePlayItem;
-(void)_updateActivityItem;
-(void)_updateCallForwardingItem;
-(void)_updateVPNItem;
-(void)_updateTTYItem;
-(void)_updateBluetoothBatteryItem;
-(void)_updateBluetoothItem;
-(void)_updateBatteryItems;
-(void)_updateDataNetworkItem;
-(void)_updateServiceItem;
-(void)_updateSignalStrengthItem;
-(void)_updateAirplaneMode;
-(void)_updateTimeItem;
-(void)_updateTimeString;
-(void)_postData;
-(void)_dataChanged;
-(const XXStruct_dUflDB*)currentData;
-(void)resetData;
-(void)setThermalColor:(int)color sunlightMode:(BOOL)mode;
-(void)setTimeCloaked:(BOOL)cloaked;
-(void)setAllItemsExceptBatteryCloaked:(BOOL)cloaked;
-(void)setTelephonyAndBluetoothItemsCloaked:(BOOL)cloaked;
-(void)_updateCloakedItems;
-(void)setShowsSyncActivityIndicator:(BOOL)indicator;
-(void)setShowsActivityIndicatorEverywhere:(BOOL)everywhere;
-(void)setShowsActivityIndicatorOnHomeScreen:(BOOL)screen;
-(void)setShowsActivityIndicatorForNewsstand:(BOOL)newsstand;
-(void)enableTime:(BOOL)time crossfade:(BOOL)crossfade crossfadeDuration:(double)duration;
-(void)enableTime:(BOOL)time;
-(BOOL)isTimeEnabled;
-(void)sendStatusBarActions:(int)actions;
-(void)updateStatusBarItem:(int)item;
-(BOOL)setStatusBarItem:(int)item enabled:(BOOL)enabled;
-(void)endUpdateBlock;
-(void)beginUpdateBlock;
-(void)dealloc;
-(id)init;
@end

