/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBThermalWarningSuppressionAssertionDelegate <NSObject>
-(void)thermalWarningAssertionExpired:(id)expired;
@end

