/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBThermalLockoutView : XXUnknownSuperclass {
	UIView* _backgroundView;
}
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

