/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBThermalWarningAlertItemDelegate <NSObject>
-(void)thermalWarningAlert:(id)alert didTriggerAction:(int)action;
@end

