/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBThermalWarningSuppressionAssertionDelegate.h"
#import "SBThermalWarningAlertItemDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSDictionary;

__attribute__((visibility("hidden")))
@interface SBThermalController : XXUnknownSuperclass <SBThermalWarningSuppressionAssertionDelegate, SBThermalWarningAlertItemDelegate> {
	BOOL _sampling;
	double _samplingStartTime;
	NSDictionary* _samplingStartCPUTimesByApp;
	int _sunlightStateToken;
	int _warningAssertionToken;
	int _warningResponseToken;
	NSMutableSet* _warningSuppressionAssertions;
	BOOL _warningSuppressionPreference;
}
+(void)logThermalEvent:(id)event;
+(id)sharedInstance;
-(void)thermalWarningAlert:(id)alert didTriggerAction:(int)action;
-(void)thermalWarningAssertionExpired:(id)expired;
-(BOOL)captureWarningSuppressionAssertionWithPort:(unsigned)port reason:(id)reason;
-(void)_didReceiveWarningAction:(int)action;
-(void)_calculateAppsCPUTimesWithCompletion:(id)completion;
-(void)_killThermallyActiveApplication;
-(void)_killThermallyActiveApplicationGivenCPUTimes:(id)times;
-(void)_beginThermalJetsamCPUSampling;
-(void)respondToCurrentThermalCondition;
-(void)showThermalAlertIfNecessary;
-(void)startListeningForThermalEvents;
-(void)dealloc;
-(id)init;
@end

