/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication;

__attribute__((visibility("hidden")))
@interface SBToAppWorkspaceTransaction : SBWorkspaceTransaction {
	SBApplication* _toApp;
	BOOL _activateSuspended;
	double _watchdogExtension;
	BOOL _fromAssistant;
	SBApplication* _toApplication;
}
@property(retain, nonatomic) SBApplication* toApplication;
-(void)_commit;
-(void)_captureApplicationData:(id)data;
-(BOOL)_shouldBeWatchdogged:(id*)watchdogged;
-(double)_watchdogInterval;
-(void)_transactionComplete;
-(void)toggleStatusBarForCleanup;
-(void)performToAppStateCleanup;
-(BOOL)shouldAnimateOrientationChangeOnCompletion;
-(BOOL)shouldDismissShowcase;
-(BOOL)shouldPerformToAppStateCleanupOnCompletion;
-(BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
-(BOOL)shouldHideSpringBoardStatusBarOnCleanup;
-(id)debugDescription;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace alertManager:(id)manager toApplication:(id)application;
@end

