/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBSlidingAlertDisplay.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay {
}
+(id)bottomBarForInstance:(id)instance;
+(id)topBarForInstance:(id)instance;
-(void)_ignore:(id)ignore;
-(void)_chooseTTYMode:(id)mode;
-(void)_chooseVoiceMode:(id)mode;
-(void)_makeCall;
-(id)initWithSize:(CGSize)size;
@end

