/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomUpApp.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromPhone : SBUIAnimationZoomUpApp {
}
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(XXStruct_UhFvxB)fakeStatusBarInfoWithStartStyle:(int)startStyle startOrientation:(int)orientation;
-(void)dealloc;
@end

