/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIPluginViewController <NSObject>
-(void)viewDidRotateFromInterfaceOrientation:(int)view;
-(void)viewWillAnimateRotationToInterfaceOrientation:(int)view;
-(void)viewWillRotateToInterfaceOrientation:(int)view;
-(void)viewDidDisappear;
-(void)viewWillDisappear;
-(void)viewDidAppear;
-(void)viewWillAppear;
-(id)view;
@optional
-(Class)popoverClass;
@end

