/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomDownApp.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomDownAppToPhone : SBUIAnimationZoomDownApp {
	BOOL _usingSuperZoomImplementation;
}
-(void)_applicationDependencyStateChanged;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(BOOL)_shouldZoomUsingSuperImplementation;
-(id)_animationProgressDependency;
-(void)dealloc;
-(void)_cleanupPhonesContextHostView;
-(XXStruct_UhFvxB)fakeStatusBarInfoWithStartEffectivelyHidden:(BOOL)startEffectivelyHidden endStyle:(int)style endOrientation:(int)orientation;
@end

