/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationController.h"
#import "SpringBoard-Structs.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpApp : SBUIAnimationController {
	UIView* _viewToAnimate;
	UIView* _contextHostView;
	BOOL _requiresHostView;
	BOOL _activateBeforeHosting;
	BOOL _animateBanner;
	BOOL _doFadeInsteadOfZoom;
	XXStruct_UhFvxB _fakeStatusBarInfo;
	BOOL _fadeOrScatterSpringBoardIfNecessary;
}
@property(assign, nonatomic) BOOL fadeOrScatterSpringBoardIfNecessary;
-(void)animationDidStop:(id)animation finished:(id)finished context:(void*)context;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(id)_animationProgressDependency;
-(BOOL)_animationShouldStart;
-(XXStruct_UhFvxB)fakeStatusBarInfoWithStartStyle:(int)startStyle startOrientation:(int)orientation;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp;
@end

