/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBUIRootView : XXUnknownSuperclass {
	BOOL _animatingAlpha;
}
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setAlpha:(float)alpha;
-(void)_actuallySetAlpha:(float)alpha;
-(id)initWithFrame:(CGRect)frame;
@end

