/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBUIFullscreenAnimationViewDelegate
-(void)appTransitionViewAnimationDidStop:(id)appTransitionViewAnimation;
-(void)appTransitionView:(id)view animationWillStartWithDuration:(double)animation afterDelay:(double)delay;
@end

