/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"

@class SBUIFullscreenAlertController, SBAlertView;

__attribute__((visibility("hidden")))
@interface SBUIFullscreenAlertAdapter : SBAlert {
	SBUIFullscreenAlertController* _alertController;
	SBAlertView* _alertDisplay;
	BOOL _animatingDeactivation;
}
-(id)description;
-(void)launchSucceeded:(BOOL)succeeded;
-(void)handleAutoLock;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(BOOL)handleVolumeDownButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleLockButtonPressed;
-(BOOL)handleMenuButtonTap;
-(BOOL)dismissPresentedModalAlertIfNecessary;
-(void)presentAlertModally:(id)modally;
-(void)alertWindow:(id)window didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)alertWindow:(id)window willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)alertWindow:(id)window willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)alertWindow:(id)window resizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
-(id)alertController;
-(void)_updateForTransparentDismiss:(id)transparentDismiss;
-(void)_pluginViewAnimatedOut:(id)anOut;
-(void)animateViewOut;
-(void)prepareViewToAnimateOut;
-(BOOL)currentlyAnimatingDeactivation;
-(void)setViewShouldAnimateIn:(BOOL)animateIn;
-(BOOL)viewDisplaysAboveStatusBar;
-(BOOL)viewIsReadyToBeRemoved;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)dealloc;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(BOOL)hasTranslucentBackground;
-(BOOL)allowsEventOnlySuspension;
-(id)initWithAlertController:(id)alertController;
@end

