/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIFullscreenAnimationView.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface SBUISlideAppTransitionView : SBUIFullscreenAnimationView {
	UIView* _fromView;
	UIView* _toView;
}
-(void)appSlideAnimationDidStop:(id)appSlideAnimation finished:(id)finished context:(void*)context;
-(void)endTransition;
-(void)beginTransition;
-(void)beginTransitionWithDuration:(double)duration delay:(double)delay;
-(void)setToView:(id)view;
-(void)setFromView:(id)view;
-(void)dealloc;
@end

