/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIAnimationControllerDelegate <NSObject>
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller didCommitAnimation:(BOOL)animation withDuration:(double)duration afterDelay:(double)delay;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
@end

