/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertView.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface SBUIFullscreenAlertViewAdapter : SBAlertView {
	BOOL _revealedContentBeneathForDismiss;
	UIView* _alertView;
}
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)alertWindowResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
-(void)setShouldAnimateIn:(BOOL)animateIn;
-(void)dismiss;
-(void)updateSpringBoardInPreparationForTransparentDismiss;
-(void)viewAnimatedOut;
-(BOOL)shouldAnimateIconsIn;
-(void)alertDisplayWillBecomeVisible;
-(BOOL)displaysAboveStatusBar;
-(BOOL)isReadyToBeRemovedFromView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame andContentView:(id)view;
-(id)_alertAdapter;
@end

