/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationController.h"


__attribute__((visibility("hidden")))
@interface SBUINullAnimationController : SBUIAnimationController {
}
-(BOOL)_isNullAnimation;
@end

