/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIBannerSourceManager <NSObject>
-(void)dismissCurrentBannerItemForSource:(id)source;
-(id)currentBannerItemForSource:(id)source;
-(void)signalSource:(id)source;
-(void)unregisterSource:(id)source;
-(void)registerSource:(id)source;
@end

