/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


__attribute__((visibility("hidden")))
@interface SBUserInstalledApplicationIcon : SBApplicationIcon {
	BOOL _shouldHaveSash;
}
-(id)badgeTextForLocation:(int)location;
-(int)accessoryTypeForLocation:(int)location;
-(void)_checkHasBeenLaunchedState;
-(BOOL)_shouldShowSashForNewlyInstalledApp;
-(id)_newlyInstalledSashLabel;
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitle;
-(id)ratingsAlertRateButtonTitle;
-(id)ratingsAlertSkipTitle;
-(id)ratingsAlertBody;
-(id)ratingsAlertTitle;
-(BOOL)hasBeenSyncedBackToITunes;
-(BOOL)allowsUninstall;
-(id)initWithApplication:(id)application;
@end

