/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBVoiceDisabledBundles : XXUnknownSuperclass {
}
+(BOOL)voiceControlDisabledByCurrentlyRunningApp;
+(void)setAppDisabledVoiceControl:(BOOL)control bundleIdentifier:(id)identifier;
@end

