/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBVoiceControlAlertDisplay.h"


__attribute__((visibility("hidden")))
@interface SBVoiceControlMenuedAlertDisplay : SBVoiceControlAlertDisplay {
}
-(BOOL)_wasTriggeredByMenu;
@end

