/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWallpaperView;

__attribute__((visibility("hidden")))
@interface SBWallpaperNotchView : XXUnknownSuperclass {
	SBWallpaperView* _wallpaperView;
	XXStruct_9ihRqB _notchInfo;
}
-(void)drawRect:(CGRect)rect;
-(void)setNotchInfo:(XXStruct_9ihRqB)info;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame wallpaperView:(id)view notchInfo:(XXStruct_9ihRqB)info;
@end

