/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBWallpaperView : XXUnknownSuperclass {
	int _orientation;
	int _variant;
	UIImageView* _topGradient;
	UIImageView* _bottomGradient;
	BOOL _usesFilter;
	float _gradientAlpha;
	CGRect _wallpaperContentsRect;
}
@property(assign, nonatomic) float gradientAlpha;
@property(assign, nonatomic) float filterAlpha;
@property(assign, nonatomic) BOOL usesFilter;
@property(readonly, assign, nonatomic) int variant;
@property(assign, nonatomic) int orientation;
-(void)resetCurrentImageToWallpaper;
-(void)replaceWallpaperWithImage:(id)image;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setAlpha:(float)alpha;
-(float)alpha;
-(void)setOrientation:(int)orientation duration:(double)duration;
-(void)_setOrientation:(int)orientation duration:(double)duration force:(BOOL)force;
-(void)_setGradientImagesWithOrientation:(int)orientation;
-(BOOL)_shouldShowGradientOverWallpaper;
-(void)_wallpaperChanged;
-(void)_resetImage;
-(void)setImage:(id)image;
-(void)dealloc;
-(id)initWithOrientation:(int)orientation variant:(int)variant;
@end

