/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBWaveView : XXUnknownSuperclass {
	float _phaseWidth;
	float _phaseShift;
	float _minAmplitude;
	float _maxAmplitude;
	float _amplitude;
	float _levelDamping;
	double _phaseDuration;
	double _amplitudeChangeTime;
	double _amplitudeChangeDuration;
	float _lastAmplitude;
	float _level;
	BOOL _animating;
}
-(void)_finishedAnimating;
-(void)stopAnimating;
-(void)beginAnimating;
-(float)_amplitudeForLevel:(float)level;
-(void)setLevelDamping:(float)damping;
-(void)setLevel:(float)level animated:(BOOL)animated;
-(void)setPhaseAnimationDuration:(double)duration;
-(void)setMaxAmplitude:(float)amplitude;
-(void)setMinAmplitude:(float)amplitude;
-(void)_setAmplitude:(float)amplitude animated:(BOOL)animated;
-(float)_currentAmplitude;
-(float)_phaseShift;
-(void)setPhaseShift:(float)shift;
-(void)setPhaseWidth:(float)width;
-(void)setColor:(id)color;
-(void)setFrame:(CGRect)frame;
@end

