/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


__attribute__((visibility("hidden")))
@interface SBWeatherApplicationIcon : SBApplicationIcon {
}
-(void)localeChanged;
@end

