/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "BBWeeAppControllerHost.h"
#import "BBWeeAppController.h"

@class NSString, UIViewController;
@protocol SBWeeAppDelegate, BBWeeAppPresentationController;

__attribute__((visibility("hidden")))
@interface SBWeeApp : XXUnknownSuperclass <BBWeeAppController, BBWeeAppControllerHost> {
	id<BBWeeAppController> _weeAppController;
	NSString* _sectionID;
	id<SBWeeAppDelegate> _delegate;
	int _presentationMode;
	UIViewController<BBWeeAppPresentationController>* _presentationController;
	BOOL _sentWillAppear;
	struct {
		unsigned viewHeight : 1;
		unsigned viewWillAppear : 1;
		unsigned viewDidAppear : 1;
		unsigned viewWillDisappear : 1;
		unsigned viewDidDisappear : 1;
		unsigned willRotate : 1;
		unsigned willAnimateRotation : 1;
		unsigned didRotate : 1;
		unsigned loadPlaceholderView : 1;
		unsigned loadFullView : 1;
		unsigned unloadView : 1;
		unsigned launchURL : 1;
		unsigned launchURLForTapLocation : 1;
		unsigned clearSnapshotImage : 1;
		unsigned host : 1;
	} _weeAppFlags;
}
@property(assign, nonatomic) id<BBWeeAppControllerHost> host;
@property(assign, nonatomic) int presentationMode;
@property(assign, nonatomic) id<SBWeeAppDelegate> delegate;
@property(readonly, assign, nonatomic) NSString* sectionID;
-(BOOL)weeApp:(id)app updatePresentationMode:(int)mode duration:(float)duration delay:(float)delay;
-(int)weeAppPresentationMode:(id)mode;
-(BOOL)weeAppWantsNotificationCenterDismissal:(id)dismissal;
-(void)weeAppWantsSizeUpdate:(id)update;
-(id)presentationControllerForMode:(int)mode;
-(void)unloadPresentationController;
-(id)currentPresentationController;
-(float)presentationHeight;
-(void)setPresentationView:(id)view;
-(void)clearShapshotImage;
-(id)launchURLForTapLocation:(CGPoint)tapLocation;
-(BOOL)wantsTaps;
-(void)unloadView;
-(void)loadFullView;
-(void)loadPlaceholderView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear;
-(void)viewWillDisappear;
-(void)viewDidAppear;
-(void)viewWillAppear;
-(float)viewHeight;
-(id)view;
-(id)description;
-(void)dealloc;
-(id)initWithWeeAppController:(id)weeAppController sectionID:(id)anId;
@end

