/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSString, NSRecursiveLock;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SBWiFiManager : XXUnknownSuperclass {
	NSRecursiveLock* _lock;
	WiFiManagerClient* _manager;
	WiFiDeviceClient* _device;
	NSString* _deviceInterfaceName;
	WiFiNetwork* _currentNetwork;
	WiFiNetwork* _previousNetwork;
	BOOL _currentNetworkHasBeenSet;
	BOOL _currentNetworkIsIOSHotspot;
	BOOL _currentNetworkIsIOSHotspotHasBeenSet;
	BOOL _powered;
	BOOL _poweredHasBeenSet;
	int _rssiThreshold;
	int _signalStrengthBars;
	int _signalStrengthRSSI;
	BOOL _signalStrengthHasBeenSet;
	SCDynamicStoreRef _SCDynamicStoreNetworkState;
	NSObject<OS_dispatch_source>* _SCUpdateTimeoutSource;
	WiFiNetwork* _primaryInterface;
	BOOL _primaryInterfaceHasBeenSet;
	BOOL _isPrimaryInterface;
	BOOL _isPrimaryInterfaceChanging;
}
+(id)sharedInstance;
-(void)_primaryInterfaceChanged:(BOOL)changed;
-(id)_wifiInterface;
-(BOOL)isPrimaryInterface;
-(void)resetSettings;
-(id)knownNetworks;
-(void)updateSignalStrength;
-(void)updateSignalStrengthFromRawRSSI:(int)rawRSSI andScaledRSSI:(float)rssi;
-(int)signalStrengthRSSI;
-(int)signalStrengthBars;
-(void)setWiFiEnabled:(BOOL)enabled;
-(BOOL)wiFiEnabled;
-(BOOL)isPowered;
-(id)currentNetworkName;
-(BOOL)_cachedIsAssociated;
-(BOOL)isAssociatedToIOSHotspot;
-(BOOL)isAssociated;
-(void)_updateCurrentNetwork;
-(void)_updateWiFiDevice:(id)device;
-(void)_linkDidChange;
-(void)_powerStateDidChange;
-(void)_updateWiFiState;
-(WiFiManagerClient*)_manager;
-(void)_setWiFiDevice:(WiFiDeviceClient*)device;
-(id)init;
@end

