/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBWorkspaceTransactionDelegate <NSObject>
-(void)transactionDidFinish:(id)transaction success:(BOOL)success;
@end

