/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBWorkspaceEventQueue;

__attribute__((visibility("hidden")))
@interface SBWorkspaceEventQueueLockAssertion : XXUnknownSuperclass {
	SBWorkspaceEventQueue* _eventQueue;
}
-(void)dealloc;
-(id)initWithWorkspaceEventQueue:(id)workspaceEventQueue;
@end

