/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderNotchView.h"


__attribute__((visibility("hidden")))
@interface SBWoodNotchView : SBFolderNotchView {
}
+(id)_squareImageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;
+(id)_keyComponentForNotchInfoRect:(CGRect)notchInfoRect;
@end

