/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAlertManager, NSMutableArray, NSDate, BKSWorkspace;
@protocol SBWorkspaceTransactionDelegate;

__attribute__((visibility("hidden")))
@interface SBWorkspaceTransaction : XXUnknownSuperclass {
	id<SBWorkspaceTransactionDelegate> _delegate;
	int _milestones;
	BKSWorkspace* _workspace;
	SBAlertManager* _alertManager;
	BOOL _didCommit;
	BOOL _completed;
	BOOL _interrupted;
	NSDate* _startTime;
	NSMutableArray* _keepAliveReasons;
}
@property(readonly, assign, nonatomic) SBAlertManager* alertManager;
@property(readonly, assign, nonatomic) BKSWorkspace* workspace;
@property(assign, nonatomic) id<SBWorkspaceTransactionDelegate> delegate;
-(BOOL)selfAlertDidDeactivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertWillDeactivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertDidActivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfAlertWillActivate:(id)selfAlert overAlerts:(id)alerts;
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(BOOL)selfApplicationActivated:(id)activated;
-(BOOL)selfApplicationDidFinishLaunching:(id)selfApplication withInfo:(id)info;
-(BOOL)selfApplicationDidStartLaunching:(id)selfApplication withInfo:(id)info;
-(BOOL)selfApplicationDidBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationWillBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfWorkspaceDidResume;
-(BOOL)selfWorkspaceWillResume;
-(BOOL)selfWorkspaceDidSuspend;
-(BOOL)selfWorkspaceWillSuspend;
-(id)_stringForInterruptReason:(int)interruptReason;
-(id)_stringForMilestones:(int)milestones;
-(void)_enumerateMilestones:(int)milestones usingBlock:(id)block;
-(id)_stringForMilestone:(int)milestone;
-(BOOL)_shouldBeWatchdogged:(id*)watchdogged;
-(double)_watchdogInterval;
-(BOOL)_enableWatchdog;
-(BOOL)alertDidDeactivate:(id)alert overAlerts:(id)alerts;
-(BOOL)alertWillDeactivate:(id)alert overAlerts:(id)alerts;
-(BOOL)alertDidActivate:(id)alert overAlerts:(id)alerts;
-(BOOL)alertWillActivate:(id)alert overAlerts:(id)alerts;
-(BOOL)applicationExited:(id)exited;
-(BOOL)applicationLaunchDidFail:(id)applicationLaunch;
-(BOOL)applicationActivated:(id)activated;
-(BOOL)applicationDidFinishLaunching:(id)application withInfo:(id)info;
-(BOOL)applicationDidStartLaunching:(id)application withInfo:(id)info;
-(BOOL)applicationDidBecomeReceiver:(id)application fromApplication:(id)application2;
-(BOOL)applicationWillBecomeReceiver:(id)application fromApplication:(id)application2;
-(BOOL)workspaceDidResume;
-(BOOL)workspaceWillResume;
-(BOOL)workspaceDidSuspend;
-(BOOL)workspaceWillSuspend;
-(void)_transactionComplete;
-(void)_interruptWithReason:(int)reason;
-(BOOL)_canBeInterrupted;
-(void)_commit;
-(void)_keepalive_async:(id)async;
-(void)_endKeepAliveForReason:(id)reason;
-(void)_keepAliveForReason:(id)reason;
-(BOOL)_hasKeepAliveReason:(id)reason;
-(BOOL)_checkAndRemoveMilestone:(int)milestone;
-(void)_notifyDelegateOfCompletion:(BOOL)completion;
-(void)removeMilestonesAndCheckForCompletion:(int)completion;
-(void)_checkAndReportIfMilestonesMet;
-(BOOL)milestonesMet;
-(BOOL)waitingForMilestone:(int)milestone;
-(void)removeMilestones:(int)milestones;
-(void)addMilestones:(int)milestones;
-(void)interruptWithReason:(int)reason;
-(void)interrupt;
-(BOOL)canBeInterrupted;
-(BOOL)completed;
-(void)commit;
-(id)description;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace alertManager:(id)manager;
@end

