/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBZoomView : XXUnknownSuperclass {
}
+(id)_chromeStatusBarImageForInterfaceOrientation:(int)interfaceOrientation;
+(CGSize)_rotateAndNormalizeSize:(CGSize)size withTransform:(CGAffineTransform)transform;
+(int)_degreesForRotationFromOriginalImageOrientation:(int)originalImageOrientation toInterfaceOrientation:(int)interfaceOrientation;
+(int)_degreesForRotationFromInterfaceOrientation:(int)interfaceOrientation toInterfaceOrientation:(int)interfaceOrientation2;
-(void)setRoundedCorners:(int)corners withCornersFrame:(CGRect)cornersFrame;
-(id)_initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
@end

