/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SPDaemonQueryDelegate
-(void)searchDaemonQueryCompleted:(id)completed;
-(void)searchDaemonQuery:(id)query encounteredError:(id)error;
-(void)searchDaemonQuery:(id)query addedResults:(id)results;
@end

