/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SPSearchAgentDelegate
@optional
-(void)searchAgentClearedResults:(id)results;
-(void)searchAgentUpdatedResults:(id)results;
@end

