/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIPopoverControllerDelegatePrivate <NSObject>
@optional
-(void)popoverController:(id)controller animationCompleted:(int)completed;
@end

