/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIPrintStatusDelegate <NSObject>
-(void)printStatusViewController:(id)controller didDismissWithCancel:(BOOL)cancel;
@optional
-(void)printStatusViewControllerJobDidCancel:(id)printStatusViewControllerJob;
@end

