/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol VSRecognitionSessionDelegate <NSObject>
@optional
-(void)recognitionSession:(id)session didCompleteActionWithError:(id)error;
-(void)recognitionSession:(id)session didFinishSpeakingFeedbackStringWithError:(id)error;
-(id)recognitionSession:(id)session openURL:(id)url;
-(void)recognitionSessionDidBeginAction:(id)recognitionSession;
-(BOOL)recognitionSessionWillBeginAction:(id)recognitionSession;
@end

