/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol XPCProxyTarget <NSObject>
-(id)proxy:(id)proxy detailedSignatureForSelector:(SEL)selector;
@end

